import { NextRequest, NextResponse } from "next/server";
import { neon } from "@neondatabase/serverless";
import { sql } from "drizzle-orm";
import { z } from "zod";
import { getDatabaseUrl } from "@/config/env";
import { getDb } from "@/db";
import { requireCasaCapability } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse, casaInternalNoStoreHeaders } from "@/server/internal/http";
import { cardObjectExists, deletePrivateCardObjectsBestEffort } from "@/server/card-production/storage";
import { cardTemplateLayoutSchema } from "@/server/card-production/template-layout";
export const dynamic="force-dynamic";
const patchSchema=z.object({schoolId:z.string().uuid(),versionLabel:z.string().trim().min(1).max(80),frontSourceKey:z.string().min(1),backSourceKey:z.string().min(1),layout:cardTemplateLayoutSchema,activate:z.boolean().default(false)});
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{templateId:string}>}){try{const access=await requireCasaCapability("MASTER_TEMPLATE_ADMIN");const{templateId}=await params;const parsed=patchSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the card template fields."},{status:400,headers:casaInternalNoStoreHeaders});const d=parsed.data;if([...d.layout.frontText,...d.layout.backText].some(x=>x.source==="CLASS"||x.source==="ACADEMIC_SESSION"))return NextResponse.json({message:"Class and Academic Session are digital-only and cannot be printed on the physical card."},{status:409,headers:casaInternalNoStoreHeaders});const db=getDb();const template=rowsOf<{school_id:string;status:string;version_label:string;front_source_key:string;back_source_key:string}>(await db.execute(sql`select school_id,status::text status,version_label,front_source_key,back_source_key from student_card_templates where id=${templateId}::uuid limit 1`))[0];if(!template)return NextResponse.json({message:"Template not found."},{status:404,headers:casaInternalNoStoreHeaders});if(template.school_id!==d.schoolId)return NextResponse.json({message:"A template cannot be moved to another school."},{status:409,headers:casaInternalNoStoreHeaders});if(template.status!=="DRAFT")return NextResponse.json({message:"Published template history is immutable. CASA will create a new internal revision when you edit the current active design."},{status:409,headers:casaInternalNoStoreHeaders});const used=rowsOf<{count:number}>(await db.execute(sql`select count(*)::int count from student_card_production_jobs where template_id=${templateId}::uuid`))[0]?.count??0;if(used>0)return NextResponse.json({message:"This draft is already referenced by card production and cannot be changed in place."},{status:409,headers:casaInternalNoStoreHeaders});const duplicate=rowsOf<{id:string}>(await db.execute(sql`select id from student_card_templates where school_id=${d.schoolId}::uuid and version_label=${d.versionLabel} and id<>${templateId}::uuid limit 1`))[0];if(duplicate)return NextResponse.json({message:"That internal template version already exists for this school."},{status:409,headers:casaInternalNoStoreHeaders});const ok=await Promise.all([cardObjectExists(d.frontSourceKey),cardObjectExists(d.backSourceKey)]);if(!ok.every(Boolean))return NextResponse.json({message:"Both uploaded card sides must exist."},{status:409,headers:casaInternalNoStoreHeaders});const client=neon(getDatabaseUrl());const layout=JSON.stringify(d.layout);const metadata=JSON.stringify({previousVersionLabel:template.version_label,versionLabel:d.versionLabel,activated:d.activate});if(d.activate){await client.transaction([
 client`update student_card_templates set status='RETIRED',activated_at=coalesce(activated_at,now()),retired_at=now(),updated_at=now() where school_id=${d.schoolId}::uuid and status='ACTIVE' and id<>${templateId}::uuid`,
 client`update student_card_templates set version_label=${d.versionLabel},front_source_key=${d.frontSourceKey},back_source_key=${d.backSourceKey},layout=${layout}::jsonb,status='ACTIVE',activated_at=now(),retired_at=null,updated_at=now() where id=${templateId}::uuid and status='DRAFT'`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${d.schoolId}::uuid,'MASTER_CARD_TEMPLATE_UPDATED_AND_ACTIVATED','CARD_TEMPLATE',${templateId}::uuid,${metadata}::jsonb,now())`
]);}else{await client.transaction([
 client`update student_card_templates set version_label=${d.versionLabel},front_source_key=${d.frontSourceKey},back_source_key=${d.backSourceKey},layout=${layout}::jsonb,updated_at=now() where id=${templateId}::uuid and status='DRAFT'`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${d.schoolId}::uuid,'MASTER_CARD_TEMPLATE_UPDATED','CARD_TEMPLATE',${templateId}::uuid,${metadata}::jsonb,now())`
]);}await deletePrivateCardObjectsBestEffort([template.front_source_key,template.back_source_key].filter(key=>key!==d.frontSourceKey&&key!==d.backSourceKey));return NextResponse.json({template:{id:templateId,schoolId:d.schoolId,versionLabel:d.versionLabel,status:d.activate?"ACTIVE":"DRAFT"},updated:true},{headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;console.error("Template update failed",error);return NextResponse.json({message:"Template could not be updated."},{status:500,headers:casaInternalNoStoreHeaders})}}
export async function DELETE(_request:NextRequest,{params}:{params:Promise<{templateId:string}>}){try{const access=await requireCasaCapability("MASTER_TEMPLATE_ADMIN");const{templateId}=await params;const db=getDb();const template=rowsOf<{school_id:string;status:string;version_label:string;front_source_key:string;back_source_key:string}>(await db.execute(sql`select school_id,status::text status,version_label,front_source_key,back_source_key from student_card_templates where id=${templateId}::uuid limit 1`))[0];if(!template)return NextResponse.json({message:"Template not found."},{status:404,headers:casaInternalNoStoreHeaders});if(template.status!=="DRAFT")return NextResponse.json({message:"Only an unused DRAFT can be deleted. Active and retired template versions remain immutable production history."},{status:409,headers:casaInternalNoStoreHeaders});const used=rowsOf<{count:number}>(await db.execute(sql`select count(*)::int count from student_card_production_jobs where template_id=${templateId}::uuid`))[0]?.count??0;if(used>0)return NextResponse.json({message:"This template version is already referenced by card production and cannot be deleted."},{status:409,headers:casaInternalNoStoreHeaders});const client=neon(getDatabaseUrl());const metadata=JSON.stringify({versionLabel:template.version_label});await client.transaction([
 client`delete from student_card_templates where id=${templateId}::uuid and status='DRAFT'`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${template.school_id}::uuid,'MASTER_CARD_TEMPLATE_DELETED','STUDENT_CARD_TEMPLATE',${templateId}::uuid,${metadata}::jsonb,now())`
]);await deletePrivateCardObjectsBestEffort([template.front_source_key,template.back_source_key]);return NextResponse.json({deleted:true},{headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;console.error("Template delete failed",error);return NextResponse.json({message:"Template could not be deleted."},{status:500,headers:casaInternalNoStoreHeaders})}}
