param(
  [string]$RepoRoot = (Get-Location).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ExpectedBranch = "main"
$ExpectedHead = "a7aa668"
$ExpectedDevelopmentHost = "ep-ancient-breeze-a52zp9gs-pooler.us-east-2.aws.neon.tech"
$ExpectedMigrationCount = 30
$PassA29Folder = "20260909020000_pass-a-enum-expansion"
$PassA30Folder = "20260909020500_pass-a-handover-attendance-state"
$PassA29Hash = "cb8d914ea1f6d54922778f7a08b7183c643cbebcc8f148b7b141daa021cf4b11"
$PassA30OriginalHash = "5eaf2d61e0e68ee0eec0911630bf3ea42185fc8548b0c3281fcc5644a630e984"
$PassA30Hash = "6ca8172dacde212cb808f126a6c30449d2395a9da292da1df69b15b255793ed0"
$PassASelftestOriginalHash = "5aeb3e9d36341ffadf68ec1d340f142d0e18307f3572346f0900aeac11ad03aa"
$PassASelftestHash = "acc657e3e93d6480cd1e56b23eb670243450568bd6f26edb75f2ea3832810ae2"
$ScannerHash = "bae161ca1d8ad1d5ccb4c24e477ff8e8f980f93dce2ac7042678b65a391fbf90"
$ScannerCssHash = "d09fdc74d3649aa6f0876ddbbfc2754cb6da2950c8171820e44860e68f9149ba"
$PackageJsonHash = "01524eb5aff5c76ede00fe8fa14bd67271264ee903b041d9fcc6cef6a06b665a"
$PackageLockHash = "1f031c58be57c0525d535881d1287666c8c059292cea9111d88ef6b8e94f7a15"
$DrizzleConfigHash = "77e9d1759af7ad1b1d3c009e7f57c6c6e25dd159a3da9907fb410552508eff80"

function ConvertTo-StringHashtable {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
    $InputObject
  )
  process {
    $table = @{}
    foreach ($property in $InputObject.PSObject.Properties) {
      $table[[string]$property.Name] = [string]$property.Value
    }
    return $table
  }
}

$MigrationManifest = @'
{"drizzle/20260827143258_school-foundation/migration.sql":"683a432f36721229e86ebe016e4d956ab3df649b702930c8c05a803e0b9be613","drizzle/20260827171725_school-auth-foundation/migration.sql":"a6d01bb226545d3f67422aa3149572b5c7cf85168269dba1fcda8e06b0e3fc36","drizzle/20260827174117_secure-login/migration.sql":"76f5468f8c2554be98e5d6969b36b36a865d4bd1adcad1b1dd200b5c8da06b63","drizzle/20260827191914_student-registry-foundation/migration.sql":"9224cc76ea86744ac79aa0a705173a007d3fdee01b2b449eb83d0ce88b9a7fb4","drizzle/20260827211507_student-id-card-lifecycle/migration.sql":"7382817a032979d577536bf9d1556f269388b105899346c9af546fc185f2f06d","drizzle/20260828003838_attendance-foundation/migration.sql":"70f2ac13858e78bc7f668e99fa7f1b3cfcee14d33f20b12326e0c57a9a1ba452","drizzle/20260828014547_student-identity-operating-model/migration.sql":"981a83662ea810c1e00cbadc0c19fcbfe6a75624e194581bfe23c495c8a230fb","drizzle/20260828015513_presence-school-messaging/migration.sql":"5d4ef2848c3190328c104c8924303b8618f1835e9bae7bf6ae4c892d7588eab8","drizzle/20260828020702_scanner-trust-card-resolution/migration.sql":"346fb3e397be6c89ddae30982801d4b288e17f07a08c746cd9104ee851c030c4","drizzle/20260828022058_trusted-biometric-presence-finalization/migration.sql":"bf672317df4f953d3ef55763589ae2d961673405532254de68940e139108bb33","drizzle/20260828024845_passkey-identity-step-up/migration.sql":"070aebf19da8eb13a3287a0530310a111c109fe4d44b478a71652acefff59aba","drizzle/20260828030204_face-enrollment-biometric-gateway/migration.sql":"fc244d51841bac5873f30fc70c943abac0470f5ae7381b155ba5115a38e13dcc","drizzle/20260828032347_aws-rekognition-biometric-engine/migration.sql":"5738c4a86b86cd588072f0c4bc5121a2ec496d47e483d153fa8a516295453591","drizzle/20260828103906_attendance-operations-supervised-exceptions/migration.sql":"2d011422410a7ee64c498a9f9e056331c536ee059e6dea2690c8564d70c1ec58","drizzle/20260829002614_equal_sabra/migration.sql":"743027f1b2f533b12a2ca498a6adaf108e6138785ddab46bc705fcc749ffb279","drizzle/20260829120249_school-scoped-card-templates/migration.sql":"4b80bbe96046dd86ff07ab727393df8a87db461817239cd3cbb12bf098db80a1","drizzle/20260830031700_school-real-world-foundation/migration.sql":"a5caed6e5750af3282570dc44c8c678dc31e46a7aabc269d57c76b03599b1b66","drizzle/20260830143000_card-production-authority/migration.sql":"ef109d255d53a2f6a7c729a9ab0d7bf93208f82f9957e9a87769bf6201893b44","drizzle/20260830153500_identity-card-lifecycle-authority/migration.sql":"b6f3c065c9055b65f6669afb3e6f567612764bc0bf4653ee91b5a36994df9a8d","drizzle/20260831064829_post-migration19-snapshot-baseline/migration.sql":"63e0a9f759662885c6a1d350596b957c6765d0ded53467f4475a8ebcfd78f9a6","drizzle/20260831064909_teacher-my-class-assignment/migration.sql":"d0f080bc0bd5256416d1dc61e74a4cf1bd5e7fa2caa9b9e7f28fe44d2d8f4f27","drizzle/20260901081825_attendance-readiness-card-replacement/migration.sql":"085bff90afedaa894f4eb77e03f2a46b38bc8b410bbbef6bbef4f06d3abd5f3b","drizzle/20260902190300_wave1_transport_casa_internal/migration.sql":"5bbde238a3a791e488f0dceeab4d98996e57dbe21ac3717cde35b2c25f034aa3","drizzle/20260902201500_wave2_structure_audit/migration.sql":"96ea98960aed00d4fca194403b54c8b8c6137e1937783b837bb38c980df0334f","drizzle/20260905030000_internal_face_authority/migration.sql":"cab5de3c1b8bf69d6148b529a1bafcda7860c9037bd17d251ed179c9f9a28dd7","drizzle/20260907043140_attendance-session-reopen/migration.sql":"881c3d9c742a5eb16e699632d95dd5cdc5321dc07de356d29add6e9b4ce980bd","drizzle/20260907105900_attendance-session-event-stream-multicycle/migration.sql":"bb708c2702a5165549447b9b91d176ded1a3a03f79ddb37332959a1181fcc0a4","drizzle/20260908135855_attendance-session-policy-rebind/migration.sql":"7791abd6bcf90d2038e434fb7e6334d98a38d19c9f14c1f2871d03f27e498681"}
'@ | ConvertFrom-Json | ConvertTo-StringHashtable

$PayloadManifest = @'
{"drizzle/20260909020000_pass-a-enum-expansion/migration.sql":"cb8d914ea1f6d54922778f7a08b7183c643cbebcc8f148b7b141daa021cf4b11","drizzle/20260909020000_pass-a-enum-expansion/snapshot.json":"416ec7cae9e355cfe7efc8c146dbd18f57b1762d8500a13d94b7b75541594db9","drizzle/20260909020500_pass-a-handover-attendance-state/migration.sql":"5eaf2d61e0e68ee0eec0911630bf3ea42185fc8548b0c3281fcc5644a630e984","drizzle/20260909020500_pass-a-handover-attendance-state/snapshot.json":"a68e2d14eb825fa82b9b8979b88f0bb3363bdbac58ee0b7eb55cb92ae91626e7","scripts/pass-a-selftest.ts":"5aeb3e9d36341ffadf68ec1d340f142d0e18307f3572346f0900aeac11ad03aa","src/app/api/internal/card-production/templates/route.ts":"4d555243e647f41dc593b33f0e77cf54d10ad1d20829b35cf094f4ae41cdf0a0","src/app/api/internal/onboarding/schools/[schoolId]/academic-options/route.ts":"3bffa0153e54b80aa701eb65698521c5411ef15a1615fe4d711b857cef551778","src/app/api/internal/onboarding/schools/[schoolId]/students/[studentId]/enrollment/route.ts":"4c88bb5c8c14557fd43a849a64c3a2f46007dc179b399b2bbee90670662fcd5f","src/app/api/schools/[slug]/attendance/card-exceptions/[studentId]/route.ts":"facfc64a1a670c5149eb4b13bcabfca208b5cf1a9ae8af1ee952bdda977af772","src/app/api/schools/[slug]/attendance/first-card-exceptions/[studentId]/route.ts":"90fdba8bd027a59139fd0afcfdb608830254afb702a8511032ebf1f2565ca090","src/app/api/schools/[slug]/attendance/lifecycle/route.ts":"6caf76298eb24fb4654217274b239c51fd4c87efcda3c7d31e12625c0c2f2944","src/app/api/schools/[slug]/attendance/supervised-late-arrivals/[studentId]/route.ts":"ff03c15701af7138bb3885a50d370de2c1386aba9188d30f80be4d7f9a64cb18","src/app/api/schools/[slug]/registry/students/[studentId]/arrival-method/route.ts":"5517695f9c2d4e5816c5e82c5cca68e29bc265d8f7396d080ebc297618602cd1","src/app/api/schools/[slug]/registry/students/[studentId]/cards/[cardId]/activate/route.ts":"59f9143f1c57584c73ed1329ac1d6c0080947a3e7035d955daf97284c601a36c","src/app/internal/onboarding/onboarding-client.tsx":"74eccdb818be4951684fe65c179f1a2bb80be7f0b969b343d2de075a219e3b9f","src/app/schools/[slug]/attendance/attendance-client.tsx":"04ef274534fdc2c77ecd3be8a8ca65beb695b9180f51088710e17b26b83d05b9","src/app/schools/[slug]/attendance/page.tsx":"1971b15fb83f20d67c10b1413054654ffa91b653bae29538f09ada3985df799e","src/app/schools/[slug]/registry/student-cards.tsx":"e6cae0450bd18b82e646cd0c3f22279a8b09710bbba4e1fbe5fd1b4f88f66e9a","src/app/schools/[slug]/technician/attendance/page.tsx":"e642b50e0166e198d0e567db7c71ee4493d026a660a69152535c0b5899a9c7e9","src/app/schools/[slug]/technician/attendance/technician-attendance-client.tsx":"1105dacd04c67b6e6b9165227c27c967cbe316da30247a5bf302e4e7d33ee1da","src/db/schema/attendance-readiness-enums.ts":"3d7b89656c774daa46d30c9d3a9c68c1ef9285e9a3a283543082a5a08dfc8b92","src/db/schema/attendance-readiness.ts":"2f3e513a21a3dcefdfb1a5f9224722ba04b8cf793976d3a4c51d32c7779abc6d","src/db/schema/card-production.ts":"0f5438de141730ae4cce8c35a8cee693a6783a0f18402f0fa977f8fca672eb3b","src/db/schema/student-enums.ts":"d8206b6900ebf7ad812d65a0d5bd4c70cd50e15f4586703a8323ab853fc73eba","src/db/schema/student-identity.ts":"d1abbcda8b7312de43d54b1023fc1350f93ea95668ffacbf2b4fc72f3e74be8a","src/server/attendance/readiness.ts":"53d2293a7a980cf4ea71b56486192dff51ed8b69bb793394b2cd4a6e32fe18ab","src/server/attendance/supervised-arrival.ts":"6219cdf78ba5269a3026f13e22eaa88fcd7f170415899826be4db686a427a209","src/server/card-production/handover.ts":"d4494c05b3152c64b2f799fadcc76f200551e35c90fe8464c8c28516fd9dd09f","src/server/card-production/production.ts":"b6c7dbe3a578bc0effb4bcf37d410d25eaafe2c351fe7a3e62e95a2dcb16ab57","src/server/card-production/render.ts":"40551fcc8229c416089e75872e364a1edaf79ddc5e695542993f5426120a1208","src/server/card-production/renewal-production.ts":"727534f212e35aefa58e3096f6618f16f72c7258e2093abd664f60843146c77d","src/server/card-production/template-layout.ts":"8775abe86433e52d18efe53beccf46e45e810fcc32ab5f7ac327c9d38960115c","src/server/internal/onboarding.ts":"b8ddbb9e66781e74f942b616f1d67bdc5acee4dadb800df67c4c7abfa8c93c22","src/server/school-operations/progression.ts":"be209773078201502f225244d62517a32adaeddce077537419b67118c335c8bd"}
'@ | ConvertFrom-Json | ConvertTo-StringHashtable

$NewPaths = @'
["drizzle/20260909020000_pass-a-enum-expansion/migration.sql","drizzle/20260909020000_pass-a-enum-expansion/snapshot.json","drizzle/20260909020500_pass-a-handover-attendance-state/migration.sql","drizzle/20260909020500_pass-a-handover-attendance-state/snapshot.json","scripts/pass-a-selftest.ts","src/app/api/schools/[slug]/attendance/first-card-exceptions/[studentId]/route.ts","src/app/api/schools/[slug]/attendance/supervised-late-arrivals/[studentId]/route.ts","src/app/api/schools/[slug]/registry/students/[studentId]/cards/[cardId]/activate/route.ts","src/server/attendance/supervised-arrival.ts","src/server/card-production/handover.ts"]
'@ | ConvertFrom-Json

$CorrectedMigration30Base64 = @'
QUxURVIgVEFCTEUgInN0dWRlbnRfaWRlbnRpdHlfY2FyZHMiCiAgQUxURVIgQ09MVU1OICJzdGF0dXMiCiAgU0VUIERFRkFVTFQgJ1JFQURZX0ZPUl9BQ1RJVkFUSU9OJzo6InN0dWRlbnRfaWRlbnRpdHlfY2FyZF9zdGF0dXMiOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQ1JFQVRFIFVOSVFVRSBJTkRFWCAic3R1ZGVudF9pZGVudGl0eV9jYXJkc19vbmVfcGVuZGluZ19hY3RpdmF0aW9uX3Blcl9zdHVkZW50X2lkeCIKICBPTiAic3R1ZGVudF9pZGVudGl0eV9jYXJkcyIgVVNJTkcgYnRyZWUgKCJzY2hvb2xfaWQiLCAic3R1ZGVudF9pZCIpCiAgV0hFUkUgInN0YXR1cyIgPSAnUkVBRFlfRk9SX0FDVElWQVRJT04nOjoic3R1ZGVudF9pZGVudGl0eV9jYXJkX3N0YXR1cyI7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlcyIKICBBREQgQ09MVU1OICJzY2hlZHVsZWRfcmVzdW1lX2F0IiB0aW1lc3RhbXAgd2l0aCB0aW1lIHpvbmU7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlcyIKICBBREQgQ09MVU1OICJzY2hlZHVsZWRfcmVzdW1lX2J5X21lbWJlcnNoaXBfaWQiIHV1aWQ7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlcyIKICBBREQgQ09MVU1OICJzY2hlZHVsZWRfcmVzdW1lX3JlYXNvbiIgdmFyY2hhcigyNDApOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInNjaG9vbF9hdHRlbmRhbmNlX2xpZmVjeWNsZV9ldmVudHMiCiAgQUREIENPTFVNTiAic2NoZWR1bGVkX2ZvciIgdGltZXN0YW1wIHdpdGggdGltZSB6b25lOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInNjaG9vbF9hdHRlbmRhbmNlX2xpZmVjeWNsZXMiCiAgQUREIENPTlNUUkFJTlQgInNjaG9vbF9hdHRlbmRhbmNlX2xpZmVjeWNsZXNfc2NoZWR1bGVkX3Jlc3VtZV9ieV9mayIKICBGT1JFSUdOIEtFWSAoInNjaG9vbF9pZCIsICJzY2hlZHVsZWRfcmVzdW1lX2J5X21lbWJlcnNoaXBfaWQiKQogIFJFRkVSRU5DRVMgInB1YmxpYyIuInNjaG9vbF9tZW1iZXJzaGlwcyIoInNjaG9vbF9pZCIsICJpZCIpCiAgT04gREVMRVRFIHJlc3RyaWN0IE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlcyIKICBBREQgQ09OU1RSQUlOVCAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlc19zY2hlZHVsZWRfcmVzdW1lX2FjdG9yX2NoZWNrIgogIENIRUNLICgKICAgICgKICAgICAgInNjaGVkdWxlZF9yZXN1bWVfYXQiIGlzIG51bGwKICAgICAgYW5kICJzY2hlZHVsZWRfcmVzdW1lX2J5X21lbWJlcnNoaXBfaWQiIGlzIG51bGwKICAgICAgYW5kICJzY2hlZHVsZWRfcmVzdW1lX3JlYXNvbiIgaXMgbnVsbAogICAgKQogICAgb3IKICAgICgKICAgICAgInNjaGVkdWxlZF9yZXN1bWVfYXQiIGlzIG5vdCBudWxsCiAgICAgIGFuZCAic2NoZWR1bGVkX3Jlc3VtZV9ieV9tZW1iZXJzaGlwX2lkIiBpcyBub3QgbnVsbAogICAgKQogICk7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlcyIKICBBREQgQ09OU1RSQUlOVCAic2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlc19zY2hlZHVsZWRfcmVzdW1lX3N0YXR1c19jaGVjayIKICBDSEVDSyAoCiAgICAic2NoZWR1bGVkX3Jlc3VtZV9hdCIgaXMgbnVsbAogICAgb3IgInN0YXR1cyIgPSAnUEFVU0VEJzo6InNjaG9vbF9hdHRlbmRhbmNlX2xpZmVjeWNsZV9zdGF0dXMiCiAgKTsKLS0+IHN0YXRlbWVudC1icmVha3BvaW50CkFMVEVSIFRBQkxFICJzY2hvb2xfYXR0ZW5kYW5jZV9saWZlY3ljbGVzIgogIEFERCBDT05TVFJBSU5UICJzY2hvb2xfYXR0ZW5kYW5jZV9saWZlY3ljbGVzX3NjaGVkdWxlZF9yZXN1bWVfcmVhc29uX2NoZWNrIgogIENIRUNLICgKICAgICJzY2hlZHVsZWRfcmVzdW1lX3JlYXNvbiIgaXMgbnVsbAogICAgb3IgbGVuZ3RoKHRyaW0oInNjaGVkdWxlZF9yZXN1bWVfcmVhc29uIikpID4gMAogICk7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9hcnJpdmFsX21ldGhvZF9hc3NpZ25tZW50cyIKICBBTFRFUiBDT0xVTU4gImFzc2lnbmVkX2J5X21lbWJlcnNoaXBfaWQiIERST1AgTk9UIE5VTEw7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9hcnJpdmFsX21ldGhvZF9hc3NpZ25tZW50cyIKICBBREQgQ09MVU1OICJhc3NpZ25lZF9ieV9pbnRlcm5hbF9tZW1iZXJzaGlwX2lkIiB1dWlkOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHNfaW50ZXJuYWxfYWN0b3JfZmsiCiAgRk9SRUlHTiBLRVkgKCJhc3NpZ25lZF9ieV9pbnRlcm5hbF9tZW1iZXJzaGlwX2lkIikKICBSRUZFUkVOQ0VTICJwdWJsaWMiLiJjYXNhX2ludGVybmFsX21lbWJlcnNoaXBzIigiaWQiKQogIE9OIERFTEVURSByZXN0cmljdCBPTiBVUERBVEUgbm8gYWN0aW9uOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHNfYWN0b3JfY2hlY2siCiAgQ0hFQ0sgKAogICAgbm90ICgKICAgICAgImFzc2lnbmVkX2J5X21lbWJlcnNoaXBfaWQiIGlzIG5vdCBudWxsCiAgICAgIGFuZCAiYXNzaWduZWRfYnlfaW50ZXJuYWxfbWVtYmVyc2hpcF9pZCIgaXMgbm90IG51bGwKICAgICkKICApOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQ1JFQVRFIE9SIFJFUExBQ0UgRlVOQ1RJT04gInB1YmxpYyIuInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHNfYWN0b3JfZ3VhcmQiKCkKUkVUVVJOUyB0cmlnZ2VyCkxBTkdVQUdFIHBscGdzcWwKQVMgJCQKREVDTEFSRQogIGFjdG9yX2ZpZWxkc19jaGFuZ2VkIGJvb2xlYW4gOj0gZmFsc2U7CkJFR0lOCiAgSUYgVEdfT1AgPSAnSU5TRVJUJyBUSEVOCiAgICBhY3Rvcl9maWVsZHNfY2hhbmdlZCA6PSB0cnVlOwogIEVMU0lGIFRHX09QID0gJ1VQREFURScgVEhFTgogICAgYWN0b3JfZmllbGRzX2NoYW5nZWQgOj0KICAgICAgTkVXLiJhc3NpZ25lZF9ieV9tZW1iZXJzaGlwX2lkIiBJUyBESVNUSU5DVCBGUk9NIE9MRC4iYXNzaWduZWRfYnlfbWVtYmVyc2hpcF9pZCIKICAgICAgT1IgTkVXLiJhc3NpZ25lZF9ieV9pbnRlcm5hbF9tZW1iZXJzaGlwX2lkIiBJUyBESVNUSU5DVCBGUk9NIE9MRC4iYXNzaWduZWRfYnlfaW50ZXJuYWxfbWVtYmVyc2hpcF9pZCI7CiAgRU5EIElGOwoKICBJRiBhY3Rvcl9maWVsZHNfY2hhbmdlZCBUSEVOCiAgICBJRgogICAgICAoCiAgICAgICAgTkVXLiJhc3NpZ25lZF9ieV9tZW1iZXJzaGlwX2lkIiBpcyBudWxsCiAgICAgICAgYW5kIE5FVy4iYXNzaWduZWRfYnlfaW50ZXJuYWxfbWVtYmVyc2hpcF9pZCIgaXMgbnVsbAogICAgICApCiAgICAgIE9SCiAgICAgICgKICAgICAgICBORVcuImFzc2lnbmVkX2J5X21lbWJlcnNoaXBfaWQiIGlzIG5vdCBudWxsCiAgICAgICAgYW5kIE5FVy4iYXNzaWduZWRfYnlfaW50ZXJuYWxfbWVtYmVyc2hpcF9pZCIgaXMgbm90IG51bGwKICAgICAgKQogICAgVEhFTgogICAgICBSQUlTRSBFWENFUFRJT04KICAgICAgICAnc3R1ZGVudF9hcnJpdmFsX21ldGhvZF9hc3NpZ25tZW50cyByZXF1aXJlcyBleGFjdGx5IG9uZSBhY3RvcicKICAgICAgICBVU0lORwogICAgICAgICAgRVJSQ09ERSA9ICcyMzUxNCcsCiAgICAgICAgICBDT05TVFJBSU5UID0gJ3N0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHNfYWN0b3JfZ3VhcmQnOwogICAgRU5EIElGOwogIEVORCBJRjsKCiAgUkVUVVJOIE5FVzsKRU5EOwokJDsKLS0+IHN0YXRlbWVudC1icmVha3BvaW50CkNSRUFURSBUUklHR0VSICJzdHVkZW50X2Fycml2YWxfbWV0aG9kX2Fzc2lnbm1lbnRzX2FjdG9yX2d1YXJkX3RyaWdnZXIiCiAgQkVGT1JFIElOU0VSVCBPUiBVUERBVEUKICBPTiAic3R1ZGVudF9hcnJpdmFsX21ldGhvZF9hc3NpZ25tZW50cyIKICBGT1IgRUFDSCBST1cKICBFWEVDVVRFIEZVTkNUSU9OICJwdWJsaWMiLiJzdHVkZW50X2Fycml2YWxfbWV0aG9kX2Fzc2lnbm1lbnRzX2FjdG9yX2d1YXJkIigpOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQ1JFQVRFIFRBQkxFICJzdHVkZW50X2ZpcnN0X2NhcmRfYXR0ZW5kYW5jZV9leGNlcHRpb25zIiAoCiAgImlkIiB1dWlkIFBSSU1BUlkgS0VZIERFRkFVTFQgZ2VuX3JhbmRvbV91dWlkKCkgTk9UIE5VTEwsCiAgInNjaG9vbF9pZCIgdXVpZCBOT1QgTlVMTCwKICAic3R1ZGVudF9pZCIgdXVpZCBOT1QgTlVMTCwKICAicGVuZGluZ19jYXJkX2lkIiB1dWlkIE5PVCBOVUxMLAogICJzZXNzaW9uX2lkIiB1dWlkIE5PVCBOVUxMLAogICJhdHRlbmRhbmNlX3JlY29yZF9pZCIgdXVpZCBOT1QgTlVMTCwKICAidmVyaWZpZWRfYnlfbWVtYmVyc2hpcF9pZCIgdXVpZCBOT1QgTlVMTCwKICAidmVyaWZpY2F0aW9uX21ldGhvZCIgInN0dWRlbnRfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbl92ZXJpZmljYXRpb24iIE5PVCBOVUxMLAogICJjcmVhdGVkX2F0IiB0aW1lc3RhbXAgd2l0aCB0aW1lIHpvbmUgREVGQVVMVCBub3coKSBOT1QgTlVMTCwKICBDT05TVFJBSU5UICJzdHVkZW50X2ZpcnN0X2NhcmRfYXR0ZW5kYW5jZV9leGNlcHRpb25zX3NjaG9vbF9pZF9pZF91bmlxdWUiCiAgICBVTklRVUUoInNjaG9vbF9pZCIsICJpZCIpLAogIENPTlNUUkFJTlQgInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnNfc3R1ZGVudF9zZXNzaW9uX3VuaXF1ZSIKICAgIFVOSVFVRSgic2Nob29sX2lkIiwgInN0dWRlbnRfaWQiLCAic2Vzc2lvbl9pZCIpLAogIENPTlNUUkFJTlQgInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnNfY2FyZF9zZXNzaW9uX3VuaXF1ZSIKICAgIFVOSVFVRSgic2Nob29sX2lkIiwgInBlbmRpbmdfY2FyZF9pZCIsICJzZXNzaW9uX2lkIikKKTsKLS0+IHN0YXRlbWVudC1icmVha3BvaW50CkFMVEVSIFRBQkxFICJzdHVkZW50X2ZpcnN0X2NhcmRfYXR0ZW5kYW5jZV9leGNlcHRpb25zIgogIEFERCBDT05TVFJBSU5UICJzdHVkZW50X2ZpcnN0X2NhcmRfYXR0ZW5kYW5jZV9leGNlcHRpb25zX3N0dWRlbnRfZmsiCiAgRk9SRUlHTiBLRVkgKCJzY2hvb2xfaWQiLCAic3R1ZGVudF9pZCIpCiAgUkVGRVJFTkNFUyAicHVibGljIi4ic3R1ZGVudHMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSBjYXNjYWRlIE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9ucyIKICBBREQgQ09OU1RSQUlOVCAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9uc19jYXJkX2ZrIgogIEZPUkVJR04gS0VZICgic2Nob29sX2lkIiwgInBlbmRpbmdfY2FyZF9pZCIpCiAgUkVGRVJFTkNFUyAicHVibGljIi4ic3R1ZGVudF9pZGVudGl0eV9jYXJkcyIoInNjaG9vbF9pZCIsICJpZCIpCiAgT04gREVMRVRFIHJlc3RyaWN0IE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9ucyIKICBBREQgQ09OU1RSQUlOVCAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9uc19zZXNzaW9uX2ZrIgogIEZPUkVJR04gS0VZICgic2Nob29sX2lkIiwgInNlc3Npb25faWQiKQogIFJFRkVSRU5DRVMgInB1YmxpYyIuImF0dGVuZGFuY2Vfc2Vzc2lvbnMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSByZXN0cmljdCBPTiBVUERBVEUgbm8gYWN0aW9uOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnNfcmVjb3JkX2ZrIgogIEZPUkVJR04gS0VZICgic2Nob29sX2lkIiwgImF0dGVuZGFuY2VfcmVjb3JkX2lkIikKICBSRUZFUkVOQ0VTICJwdWJsaWMiLiJzdHVkZW50X2F0dGVuZGFuY2VfcmVjb3JkcyIoInNjaG9vbF9pZCIsICJpZCIpCiAgT04gREVMRVRFIHJlc3RyaWN0IE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9ucyIKICBBREQgQ09OU1RSQUlOVCAic3R1ZGVudF9maXJzdF9jYXJkX2F0dGVuZGFuY2VfZXhjZXB0aW9uc192ZXJpZmllcl9mayIKICBGT1JFSUdOIEtFWSAoInNjaG9vbF9pZCIsICJ2ZXJpZmllZF9ieV9tZW1iZXJzaGlwX2lkIikKICBSRUZFUkVOQ0VTICJwdWJsaWMiLiJzY2hvb2xfbWVtYmVyc2hpcHMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSByZXN0cmljdCBPTiBVUERBVEUgbm8gYWN0aW9uOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQ1JFQVRFIElOREVYICJzdHVkZW50X2ZpcnN0X2NhcmRfYXR0ZW5kYW5jZV9leGNlcHRpb25zX3N0dWRlbnRfY3JlYXRlZF9pZHgiCiAgT04gInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnMiIFVTSU5HIGJ0cmVlCiAgKCJzY2hvb2xfaWQiLCAic3R1ZGVudF9pZCIsICJjcmVhdGVkX2F0Iik7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApDUkVBVEUgVEFCTEUgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzIiAoCiAgImlkIiB1dWlkIFBSSU1BUlkgS0VZIERFRkFVTFQgZ2VuX3JhbmRvbV91dWlkKCkgTk9UIE5VTEwsCiAgInNjaG9vbF9pZCIgdXVpZCBOT1QgTlVMTCwKICAiYnJhbmNoX2lkIiB1dWlkIE5PVCBOVUxMLAogICJzdHVkZW50X2lkIiB1dWlkIE5PVCBOVUxMLAogICJzZXNzaW9uX2lkIiB1dWlkIE5PVCBOVUxMLAogICJhdHRlbmRhbmNlX3JlY29yZF9pZCIgdXVpZCBOT1QgTlVMTCwKICAidmVyaWZpZWRfYnlfbWVtYmVyc2hpcF9pZCIgdXVpZCBOT1QgTlVMTCwKICAicmVhc29uIiB2YXJjaGFyKDI0MCkgTk9UIE5VTEwsCiAgIm9jY3VycmVkX2F0IiB0aW1lc3RhbXAgd2l0aCB0aW1lIHpvbmUgREVGQVVMVCBub3coKSBOT1QgTlVMTCwKICAiY3JlYXRlZF9hdCIgdGltZXN0YW1wIHdpdGggdGltZSB6b25lIERFRkFVTFQgbm93KCkgTk9UIE5VTEwsCiAgQ09OU1RSQUlOVCAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHNfc2Nob29sX2lkX2lkX3VuaXF1ZSIKICAgIFVOSVFVRSgic2Nob29sX2lkIiwgImlkIiksCiAgQ09OU1RSQUlOVCAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHNfc3R1ZGVudF9zZXNzaW9uX3VuaXF1ZSIKICAgIFVOSVFVRSgic2Nob29sX2lkIiwgInN0dWRlbnRfaWQiLCAic2Vzc2lvbl9pZCIpLAogIENPTlNUUkFJTlQgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzX3JlYXNvbl9ub3RfYmxhbmtfY2hlY2siCiAgICBDSEVDSyAobGVuZ3RoKHRyaW0oInJlYXNvbiIpKSA+IDApCik7Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzX2JyYW5jaF9mayIKICBGT1JFSUdOIEtFWSAoInNjaG9vbF9pZCIsICJicmFuY2hfaWQiKQogIFJFRkVSRU5DRVMgInB1YmxpYyIuInNjaG9vbF9icmFuY2hlcyIoInNjaG9vbF9pZCIsICJpZCIpCiAgT04gREVMRVRFIHJlc3RyaWN0IE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzX3N0dWRlbnRfZmsiCiAgRk9SRUlHTiBLRVkgKCJzY2hvb2xfaWQiLCAic3R1ZGVudF9pZCIpCiAgUkVGRVJFTkNFUyAicHVibGljIi4ic3R1ZGVudHMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSBjYXNjYWRlIE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzX3Nlc3Npb25fZmsiCiAgRk9SRUlHTiBLRVkgKCJzY2hvb2xfaWQiLCAic2Vzc2lvbl9pZCIpCiAgUkVGRVJFTkNFUyAicHVibGljIi4iYXR0ZW5kYW5jZV9zZXNzaW9ucyIoInNjaG9vbF9pZCIsICJpZCIpCiAgT04gREVMRVRFIHJlc3RyaWN0IE9OIFVQREFURSBubyBhY3Rpb247Ci0tPiBzdGF0ZW1lbnQtYnJlYWtwb2ludApBTFRFUiBUQUJMRSAic3R1ZGVudF9zdXBlcnZpc2VkX2xhdGVfYXJyaXZhbHMiCiAgQUREIENPTlNUUkFJTlQgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzX3JlY29yZF9mayIKICBGT1JFSUdOIEtFWSAoInNjaG9vbF9pZCIsICJhdHRlbmRhbmNlX3JlY29yZF9pZCIpCiAgUkVGRVJFTkNFUyAicHVibGljIi4ic3R1ZGVudF9hdHRlbmRhbmNlX3JlY29yZHMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSByZXN0cmljdCBPTiBVUERBVEUgbm8gYWN0aW9uOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQUxURVIgVEFCTEUgInN0dWRlbnRfc3VwZXJ2aXNlZF9sYXRlX2Fycml2YWxzIgogIEFERCBDT05TVFJBSU5UICJzdHVkZW50X3N1cGVydmlzZWRfbGF0ZV9hcnJpdmFsc192ZXJpZmllcl9mayIKICBGT1JFSUdOIEtFWSAoInNjaG9vbF9pZCIsICJ2ZXJpZmllZF9ieV9tZW1iZXJzaGlwX2lkIikKICBSRUZFUkVOQ0VTICJwdWJsaWMiLiJzY2hvb2xfbWVtYmVyc2hpcHMiKCJzY2hvb2xfaWQiLCAiaWQiKQogIE9OIERFTEVURSByZXN0cmljdCBPTiBVUERBVEUgbm8gYWN0aW9uOwotLT4gc3RhdGVtZW50LWJyZWFrcG9pbnQKQ1JFQVRFIElOREVYICJzdHVkZW50X3N1cGVydmlzZWRfbGF0ZV9hcnJpdmFsc19icmFuY2hfb2NjdXJyZWRfaWR4IgogIE9OICJzdHVkZW50X3N1cGVydmlzZWRfbGF0ZV9hcnJpdmFscyIgVVNJTkcgYnRyZWUKICAoInNjaG9vbF9pZCIsICJicmFuY2hfaWQiLCAib2NjdXJyZWRfYXQiKTsK
'@
$CorrectedPassASelftestBase64 = @'
aW1wb3J0IGZzIGZyb20gIm5vZGU6ZnMiOwppbXBvcnQgcGF0aCBmcm9tICJub2RlOnBhdGgiOwoKZnVuY3Rpb24gYXNzZXJ0KGNvbmRpdGlvbjogdW5rbm93biwgbWVzc2FnZTogc3RyaW5nKTogYXNzZXJ0cyBjb25kaXRpb24gewogIGlmICghY29uZGl0aW9uKSB7CiAgICB0aHJvdyBuZXcgRXJyb3IoYFBBU1NfQV9TRUxGVEVTVF9GQUlMRUQ6ICR7bWVzc2FnZX1gKTsKICB9Cn0KCmNvbnN0IHJvb3QgPSBwcm9jZXNzLmN3ZCgpOwpjb25zdCByZWFkID0gKHJlbGF0aXZlOiBzdHJpbmcpID0+CiAgZnMucmVhZEZpbGVTeW5jKHBhdGguam9pbihyb290LCByZWxhdGl2ZSksICJ1dGY4Iik7CmNvbnN0IGNvbnRhaW5zID0gKHJlbGF0aXZlOiBzdHJpbmcsIHZhbHVlOiBzdHJpbmcpID0+CiAgcmVhZChyZWxhdGl2ZSkuaW5jbHVkZXModmFsdWUpOwoKY29uc3QgZW51bXMgPSByZWFkKCJzcmMvZGIvc2NoZW1hL3N0dWRlbnQtZW51bXMudHMiKTsKYXNzZXJ0KGVudW1zLmluY2x1ZGVzKCciUkVBRFlfRk9SX0FDVElWQVRJT04iJyksICJjYXJkIHBlbmRpbmctaGFuZG92ZXIgZW51bSBtaXNzaW5nIik7CmFzc2VydChlbnVtcy5pbmNsdWRlcygnIkFDVElWQVRFRCInKSwgImNhcmQgYWN0aXZhdGlvbiBldmVudCBlbnVtIG1pc3NpbmciKTsKCmNvbnN0IGlkZW50aXR5ID0gcmVhZCgic3JjL2RiL3NjaGVtYS9zdHVkZW50LWlkZW50aXR5LnRzIik7CmFzc2VydChpZGVudGl0eS5pbmNsdWRlcygnLmRlZmF1bHQoIlJFQURZX0ZPUl9BQ1RJVkFUSU9OIiknKSwgIm5ldyBjYXJkIGRlZmF1bHQgaXMgbm90IFJFQURZX0ZPUl9BQ1RJVkFUSU9OIik7CmFzc2VydChpZGVudGl0eS5pbmNsdWRlcygic3R1ZGVudF9pZGVudGl0eV9jYXJkc19vbmVfcGVuZGluZ19hY3RpdmF0aW9uX3Blcl9zdHVkZW50X2lkeCIpLCAicGVuZGluZy1jYXJkIHVuaXF1ZW5lc3MgZ3VhcmQgbWlzc2luZyIpOwoKY29uc3QgcHJvZHVjdGlvbiA9IHJlYWQoInNyYy9zZXJ2ZXIvY2FyZC1wcm9kdWN0aW9uL3Byb2R1Y3Rpb24udHMiKTsKYXNzZXJ0KC9hY2FkZW1pY1Nlc3Npb246XHMqbnVsbCwvLnRlc3QocHJvZHVjdGlvbiksICJub3JtYWwgcHJvZHVjdGlvbiBzdGlsbCBzbmFwc2hvdHMgQWNhZGVtaWMgU2Vzc2lvbiIpOwphc3NlcnQocHJvZHVjdGlvbi5pbmNsdWRlcygiJ1JFQURZX0ZPUl9BQ1RJVkFUSU9OJzo6c3R1ZGVudF9pZGVudGl0eV9jYXJkX3N0YXR1cyIpLCAibm9ybWFsIHByb2R1Y3Rpb24gZG9lcyBub3QgY3JlYXRlIHBlbmRpbmctaGFuZG92ZXIgY2FyZHMiKTsKCmNvbnN0IGhhbmRvdmVyID0gcmVhZCgic3JjL3NlcnZlci9jYXJkLXByb2R1Y3Rpb24vaGFuZG92ZXIudHMiKTsKZm9yIChjb25zdCBzaWduYWwgb2YgWwogICInUFJJTlRFRCc6OnN0dWRlbnRfY2FyZF9wcm9kdWN0aW9uX3N0YXR1cyIsCiAgIidSRUFEWV9GT1JfQUNUSVZBVElPTic6OnN0dWRlbnRfaWRlbnRpdHlfY2FyZF9zdGF0dXMiLAogICInUkVQTEFDRUQnOjpzdHVkZW50X2lkZW50aXR5X2NhcmRfc3RhdHVzIiwKICAiJ0FDVElWRSc6OnN0dWRlbnRfaWRlbnRpdHlfY2FyZF9zdGF0dXMiLAogICInQUNUSVZBVEVEJzo6c3R1ZGVudF9pZGVudGl0eV9jYXJkX2V2ZW50X3R5cGUiLApdKSB7CiAgYXNzZXJ0KGhhbmRvdmVyLmluY2x1ZGVzKHNpZ25hbCksIGBoYW5kb3ZlciBsaWZlY3ljbGUgc2lnbmFsIG1pc3Npbmc6ICR7c2lnbmFsfWApOwp9CmFzc2VydChoYW5kb3Zlci5pbmNsdWRlcygicmVxdWlyZUJyYW5jaEFjY2VzcyIpLCAiY2FyZCBoYW5kb3ZlciBpcyBub3QgYnJhbmNoLWF1dGhvcml6ZWQiKTsKCmNvbnN0IHN1cGVydmlzZWQgPSByZWFkKCJzcmMvc2VydmVyL2F0dGVuZGFuY2Uvc3VwZXJ2aXNlZC1hcnJpdmFsLnRzIik7CmFzc2VydChzdXBlcnZpc2VkLmluY2x1ZGVzKCdtb2RlOiAiRklSU1RfQ0FSRCInKSwgImZpcnN0LWNhcmQgYXR0ZW5kYW5jZSBwYXRoIG1pc3NpbmciKTsKYXNzZXJ0KHN1cGVydmlzZWQuaW5jbHVkZXMoIkZJUlNUX0NBUkRfUEVORElOR19IQU5ET1ZFUiIpLCAiZmlyc3QtY2FyZCBhdWRpdCByZWFzb24gbWlzc2luZyIpOwphc3NlcnQoc3VwZXJ2aXNlZC5pbmNsdWRlcygiJ01BTlVBTCc6OmF0dGVuZGFuY2VfcmVjb3JkX3N0YXR1cyIpLCAiZmlyc3QtY2FyZCBleGNlcHRpb24gbXVzdCByZW1haW4gTUFOVUFMIik7CmFzc2VydChzdXBlcnZpc2VkLmluY2x1ZGVzKCdtb2RlOiAiTEFURSInKSwgInN1cGVydmlzZWQgbGF0ZS1hcnJpdmFsIHBhdGggbWlzc2luZyIpOwphc3NlcnQoc3VwZXJ2aXNlZC5pbmNsdWRlcygiJ0xBVEUnOjphdHRlbmRhbmNlX3JlY29yZF9zdGF0dXMiKSwgImFmdGVyLXdpbmRvdyBhcnJpdmFsIGlzIG5vdCBwZXJzaXN0ZWQgYXMgTEFURSIpOwphc3NlcnQoc3VwZXJ2aXNlZC5pbmNsdWRlcygiU1VQRVJWSVNFRF9BRlRFUl9XSU5ET1dfTEFURSIpLCAic3VwZXJ2aXNlZC1sYXRlIGF1ZGl0IHJlYXNvbiBtaXNzaW5nIik7CmFzc2VydChzdXBlcnZpc2VkLmluY2x1ZGVzKCJyZXF1aXJlQnJhbmNoQWNjZXNzIiksICJzdXBlcnZpc2VkIGF0dGVuZGFuY2UgaXMgbm90IGJyYW5jaC1hdXRob3JpemVkIik7CmFzc2VydChzdXBlcnZpc2VkLmluY2x1ZGVzKCJjYXJkX2NvdW50ID0gMSIpIHx8IHN1cGVydmlzZWQuaW5jbHVkZXMoImNhcmRfY291bnQiKSwgImZpcnN0LWNhcmQtb25seSBndWFyZCBtaXNzaW5nIik7Cgpjb25zdCBsaWZlY3ljbGVSb3V0ZSA9IHJlYWQoInNyYy9hcHAvYXBpL3NjaG9vbHMvW3NsdWddL2F0dGVuZGFuY2UvbGlmZWN5Y2xlL3JvdXRlLnRzIik7CmFzc2VydChsaWZlY3ljbGVSb3V0ZS5pbmNsdWRlcygicmVxdWlyZUF0dGVuZGFuY2VNYW5hZ2VyIiksICJsaWZlY3ljbGUgbXV0YXRpb24gaXMgbm90IE93bmVyL0FkbWluIGNvbnN0cmFpbmVkIik7CmFzc2VydChsaWZlY3ljbGVSb3V0ZS5pbmNsdWRlcygnIlNDSEVEVUxFX1JFU1VNRSInKSwgInNjaGVkdWxlZCByZXN1bWUgQVBJIGFjdGlvbiBtaXNzaW5nIik7CmFzc2VydChsaWZlY3ljbGVSb3V0ZS5pbmNsdWRlcygnIkNBTkNFTF9TQ0hFRFVMRURfUkVTVU1FIicpLCAic2NoZWR1bGVkIHJlc3VtZSBjYW5jZWxsYXRpb24gbWlzc2luZyIpOwoKY29uc3QgcmVhZGluZXNzID0gcmVhZCgic3JjL3NlcnZlci9hdHRlbmRhbmNlL3JlYWRpbmVzcy50cyIpOwphc3NlcnQocmVhZGluZXNzLmluY2x1ZGVzKCJhcHBseUR1ZVNjaGVkdWxlZFJlc3VtZSIpLCAiZHVlIHNjaGVkdWxlZCByZXN1bWUgbWF0ZXJpYWxpemF0aW9uIG1pc3NpbmciKTsKYXNzZXJ0KHJlYWRpbmVzcy5pbmNsdWRlcygic2NoZWR1bGVkX3Jlc3VtZV9hdCA8PSBub3coKSIpLCAiZHVlIHNjaGVkdWxlZCByZXN1bWUgdGltZSBndWFyZCBtaXNzaW5nIik7CmFzc2VydChyZWFkaW5lc3MuaW5jbHVkZXMoIidSRVNVTUVfU0NIRURVTEVEJzo6c2Nob29sX2F0dGVuZGFuY2VfbGlmZWN5Y2xlX2V2ZW50X3R5cGUiKSwgInNjaGVkdWxlZC1yZXN1bWUgYXVkaXQgZXZlbnQgbWlzc2luZyIpOwphc3NlcnQocmVhZGluZXNzLmluY2x1ZGVzKCInUkVTVU1FX1NDSEVEVUxFX0NBTkNFTExFRCc6OnNjaG9vbF9hdHRlbmRhbmNlX2xpZmVjeWNsZV9ldmVudF90eXBlIiksICJzY2hlZHVsZWQtcmVzdW1lIGNhbmNlbGxhdGlvbiBhdWRpdCBldmVudCBtaXNzaW5nIik7Cgpjb25zdCB0ZWNobmljaWFuUGFnZSA9IHJlYWQoInNyYy9hcHAvc2Nob29scy9bc2x1Z10vdGVjaG5pY2lhbi9hdHRlbmRhbmNlL3BhZ2UudHN4Iik7CmFzc2VydCh0ZWNobmljaWFuUGFnZS5pbmNsdWRlcygncm9sZSA9PT0gIk9XTkVSIicpICYmIHRlY2huaWNpYW5QYWdlLmluY2x1ZGVzKCdyb2xlID09PSAiQURNSU4iJyksICJ0ZWNobmljaWFuIHBhZ2UgbGlmZWN5Y2xlIGF1dGhvcml0eSBnYXRlIG1pc3NpbmciKTsKYXNzZXJ0KCF0ZWNobmljaWFuUGFnZS5pbmNsdWRlcygncm9sZSA9PT0gIlNDSE9PTF9URUNITklDSUFOIiB8fCcpLCAidGVjaG5pY2lhbiBhcHBlYXJzIHRvIHJldGFpbiBsaWZlY3ljbGUgYXV0aG9yaXR5Iik7Cgpjb25zdCBvbmJvYXJkaW5nQXBpID0gcmVhZCgic3JjL2FwcC9hcGkvaW50ZXJuYWwvb25ib2FyZGluZy9zY2hvb2xzL1tzY2hvb2xJZF0vc3R1ZGVudHMvW3N0dWRlbnRJZF0vZW5yb2xsbWVudC9yb3V0ZS50cyIpOwphc3NlcnQob25ib2FyZGluZ0FwaS5pbmNsdWRlcygiYnJhbmNoSWQiKSwgIkJyYW5jaCBpcyBub3QgcmVxdWlyZWQgYnkgb25ib2FyZGluZyBBUEkiKTsKYXNzZXJ0KG9uYm9hcmRpbmdBcGkuaW5jbHVkZXMoImFycml2YWxNZXRob2QiKSwgIkFycml2YWwgTWV0aG9kIGlzIG5vdCByZXF1aXJlZCBieSBvbmJvYXJkaW5nIEFQSSIpOwphc3NlcnQob25ib2FyZGluZ0FwaS5pbmNsdWRlcygnIlNDSE9PTF9CVVMiJykgJiYgb25ib2FyZGluZ0FwaS5pbmNsdWRlcygnIklOREVQRU5ERU5UIicpLCAiYXJyaXZhbC1tZXRob2QgY2hvaWNlcyBhcmUgaW5jb21wbGV0ZSIpOwoKY29uc3Qgb25ib2FyZGluZyA9IHJlYWQoInNyYy9zZXJ2ZXIvaW50ZXJuYWwvb25ib2FyZGluZy50cyIpOwphc3NlcnQob25ib2FyZGluZy5pbmNsdWRlcygic2Nob29sX2JyYW5jaF9jbGFzc19hcm1zIiksICJvbmJvYXJkaW5nIGRvZXMgbm90IHZhbGlkYXRlIEJyYW5jaC9DbGFzcyBtYXBwaW5nIik7CmFzc2VydChvbmJvYXJkaW5nLmluY2x1ZGVzKCJhc3NpZ25lZF9ieV9pbnRlcm5hbF9tZW1iZXJzaGlwX2lkIiksICJDQVNBLWludGVybmFsIGFycml2YWwgYXR0cmlidXRpb24gbWlzc2luZyIpOwphc3NlcnQob25ib2FyZGluZy5pbmNsdWRlcygiZnJvbSB2YWxpZF9zY29wZSIpLCAib25ib2FyZGluZyB2YWxpZGF0ZWQtc2NvcGUgZ3VhcmQgbWlzc2luZyIpOwphc3NlcnQob25ib2FyZGluZy5pbmNsdWRlcygiYW5kIGV4aXN0cyAoXG4gICAgICAgICAgICBzZWxlY3QgMVxuICAgICAgICAgICAgZnJvbSB2YWxpZF9zY29wZVxuICAgICAgICAgICkiKSwgImRlc3RydWN0aXZlIG9uYm9hcmRpbmcgY2xvc2UgaXMgbm90IGdhdGVkIGJ5IHZhbGlkIHNjb3BlIik7Cgpjb25zdCBwcm9ncmVzc2lvbiA9IHJlYWQoInNyYy9zZXJ2ZXIvc2Nob29sLW9wZXJhdGlvbnMvcHJvZ3Jlc3Npb24udHMiKTsKYXNzZXJ0KHByb2dyZXNzaW9uLmluY2x1ZGVzKCInQ0xBU1NfQ0hBTkdFJzo6c3R1ZGVudF9jYXJkX3JlbmV3YWxfcmVhc29uIiksICJwcm9ncmVzc2lvbiBkb2VzIG5vdCBjcmVhdGUgY2xhc3MtY2hhbmdlIHJlbmV3YWwgcmVhc29uIik7CmFzc2VydChwcm9ncmVzc2lvbi5pbmNsdWRlcygic291cmNlX2NsYXNzX2FybV9pZCA8PiB0YXJnZXRfY2xhc3NfYXJtX2lkIiksICJyZW5ld2FsIGludGVncml0eSBpcyBub3QgY2xhc3MtY2hhbmdlLW9ubHkiKTsKCmNvbnN0IHJlbmV3YWwgPSByZWFkKCJzcmMvc2VydmVyL2NhcmQtcHJvZHVjdGlvbi9yZW5ld2FsLXByb2R1Y3Rpb24udHMiKTsKYXNzZXJ0KC9yZW5ld2FsSXRlbVwucmVhc29uXHMqIT09XHMqIkNMQVNTX0NIQU5HRSIvLnRlc3QocmVuZXdhbCksICJyZW5ld2FsIHJlbmRlcmVyIGFjY2VwdHMgbm9uLWNsYXNzLWNoYW5nZSByZWFzb25zIik7CmFzc2VydCgvYWNhZGVtaWNTZXNzaW9uOlxzKm51bGwsLy50ZXN0KHJlbmV3YWwpLCAicmVuZXdhbCBwcm9kdWN0aW9uIHN0aWxsIHNuYXBzaG90cyBBY2FkZW1pYyBTZXNzaW9uIik7CmFzc2VydChyZW5ld2FsLmluY2x1ZGVzKCInUkVBRFlfRk9SX0FDVElWQVRJT04nOjpzdHVkZW50X2lkZW50aXR5X2NhcmRfc3RhdHVzIiksICJyZW5ld2FsIHByb2R1Y3Rpb24gYnlwYXNzZXMgaGFuZG92ZXIgYWN0aXZhdGlvbiIpOwoKY29uc3QgdGVtcGxhdGVSb3V0ZSA9IHJlYWQoInNyYy9hcHAvYXBpL2ludGVybmFsL2NhcmQtcHJvZHVjdGlvbi90ZW1wbGF0ZXMvcm91dGUudHMiKTsKYXNzZXJ0KHRlbXBsYXRlUm91dGUuaW5jbHVkZXMoIkNBUkRfVEVNUExBVEVfQUNBREVNSUNfU0VTU0lPTl9GT1JCSURERU4iKSwgIm5ldyB0ZW1wbGF0ZXMgY2FuIHN0aWxsIHJlZ2lzdGVyIEFjYWRlbWljIFNlc3Npb24iKTsKCmNvbnN0IHJlbmRlciA9IHJlYWQoInNyYy9zZXJ2ZXIvY2FyZC1wcm9kdWN0aW9uL3JlbmRlci50cyIpOwphc3NlcnQocmVuZGVyLmluY2x1ZGVzKCJBQ0FERU1JQ19TRVNTSU9OOlxuICAgICAgICBcIlwiIiksICJsZWdhY3kgQWNhZGVtaWMgU2Vzc2lvbiBpcyBub3Qgc3VwcHJlc3NlZCBhdCByZW5kZXIgdGltZSIpOwphc3NlcnQocmVuZGVyLmluY2x1ZGVzKCJmdW5jdGlvbiBmaXRUZXh0KCIpLCAiYm91bmRlZCB0ZXh0IGZpdHRpbmcgbWlzc2luZyIpOwphc3NlcnQocmVuZGVyLmluY2x1ZGVzKCJmdW5jdGlvbiB3cmFwVGV4dCgiKSwgImJvdW5kZWQgdGV4dCB3cmFwcGluZyBtaXNzaW5nIik7CmFzc2VydChyZW5kZXIuaW5jbHVkZXMoIm1pbkZvbnRTaXplIiksICJib3VuZGVkIGZvbnQgc2hyaW5rIG1pc3NpbmciKTsKCmNvbnN0IGNhcmRQcm9kdWN0aW9uU291cmNlcyA9IFsKICAic3JjL3NlcnZlci9jYXJkLXByb2R1Y3Rpb24vdGVtcGxhdGUtbGF5b3V0LnRzIiwKICAic3JjL3NlcnZlci9jYXJkLXByb2R1Y3Rpb24vcmVuZGVyLnRzIiwKICAic3JjL2RiL3NjaGVtYS9jYXJkLXByb2R1Y3Rpb24udHMiLAogICJzcmMvc2VydmVyL2NhcmQtcHJvZHVjdGlvbi9wcm9kdWN0aW9uLnRzIiwKICAic3JjL3NlcnZlci9jYXJkLXByb2R1Y3Rpb24vcmVuZXdhbC1wcm9kdWN0aW9uLnRzIiwKXS5tYXAocmVhZCkuam9pbigiXG4iKTsKYXNzZXJ0KCEvKFNUVURFTlRfUEhPVE98c3R1ZGVudFBob3RvfHN0dWRlbnRfcGhvdG98cG9ydHJhaXRLZXl8cG9ydHJhaXRfa2V5fHBob3RvS2V5fHBob3RvX2tleSkvLnRlc3QoY2FyZFByb2R1Y3Rpb25Tb3VyY2VzKSwgImR5bmFtaWMgc3R1ZGVudC1waG90byBzb3VyY2UgZGV0ZWN0ZWQgaW4gcGh5c2ljYWwtY2FyZCBwaXBlbGluZSIpOwoKY29uc3QgbWlncmF0aW9uc0RpciA9IHBhdGguam9pbihyb290LCAiZHJpenpsZSIpOwpjb25zdCBtaWdyYXRpb25Db3VudCA9IGZzLnJlYWRkaXJTeW5jKG1pZ3JhdGlvbnNEaXIsIHsgd2l0aEZpbGVUeXBlczogdHJ1ZSB9KQogIC5maWx0ZXIoKGVudHJ5KSA9PiBlbnRyeS5pc0RpcmVjdG9yeSgpKQogIC5maWx0ZXIoKGVudHJ5KSA9PiBmcy5leGlzdHNTeW5jKHBhdGguam9pbihtaWdyYXRpb25zRGlyLCBlbnRyeS5uYW1lLCAibWlncmF0aW9uLnNxbCIpKSkKICAubGVuZ3RoOwphc3NlcnQobWlncmF0aW9uQ291bnQgPT09IDMwLCBgZXhwZWN0ZWQgMzAgbWlncmF0aW9ucyBhZnRlciBQYXNzIEEsIGZvdW5kICR7bWlncmF0aW9uQ291bnR9YCk7Cgpjb25zdCBlbnVtTWlncmF0aW9uID0gcmVhZCgiZHJpenpsZS8yMDI2MDkwOTAyMDAwMF9wYXNzLWEtZW51bS1leHBhbnNpb24vbWlncmF0aW9uLnNxbCIpOwpjb25zdCBzdGF0ZU1pZ3JhdGlvbiA9IHJlYWQoImRyaXp6bGUvMjAyNjA5MDkwMjA1MDBfcGFzcy1hLWhhbmRvdmVyLWF0dGVuZGFuY2Utc3RhdGUvbWlncmF0aW9uLnNxbCIpOwphc3NlcnQoZW51bU1pZ3JhdGlvbi5pbmNsdWRlcygiUkVBRFlfRk9SX0FDVElWQVRJT04iKSAmJiBlbnVtTWlncmF0aW9uLmluY2x1ZGVzKCJSRVNVTUVfU0NIRURVTEVEIiksICJlbnVtLWV4cGFuc2lvbiBtaWdyYXRpb24gaW5jb21wbGV0ZSIpOwphc3NlcnQoc3RhdGVNaWdyYXRpb24uaW5jbHVkZXMoInN0dWRlbnRfZmlyc3RfY2FyZF9hdHRlbmRhbmNlX2V4Y2VwdGlvbnMiKSwgImZpcnN0LWNhcmQgYXVkaXQgbWlncmF0aW9uIG1pc3NpbmciKTsKYXNzZXJ0KHN0YXRlTWlncmF0aW9uLmluY2x1ZGVzKCJzdHVkZW50X3N1cGVydmlzZWRfbGF0ZV9hcnJpdmFscyIpLCAic3VwZXJ2aXNlZC1sYXRlIGF1ZGl0IG1pZ3JhdGlvbiBtaXNzaW5nIik7CmFzc2VydChzdGF0ZU1pZ3JhdGlvbi5pbmNsdWRlcygiYXNzaWduZWRfYnlfaW50ZXJuYWxfbWVtYmVyc2hpcF9pZCIpLCAiaW50ZXJuYWwgYXJyaXZhbCBhdHRyaWJ1dGlvbiBtaWdyYXRpb24gbWlzc2luZyIpOwphc3NlcnQoc3RhdGVNaWdyYXRpb24uaW5jbHVkZXMoInN0dWRlbnRfYXJyaXZhbF9tZXRob2RfYXNzaWdubWVudHNfYWN0b3JfZ3VhcmRfdHJpZ2dlciIpLCAiZnV0dXJlIGFycml2YWwgYWN0b3IgdHJpZ2dlciBtaXNzaW5nIik7CmFzc2VydChzdGF0ZU1pZ3JhdGlvbi5pbmNsdWRlcygiVEdfT1AgPSAnSU5TRVJUJyIpLCAiYXJyaXZhbCBhY3RvciB0cmlnZ2VyIGRvZXMgbm90IGVuZm9yY2UgbmV3IGFzc2lnbm1lbnRzIik7CmFzc2VydChzdGF0ZU1pZ3JhdGlvbi5pbmNsdWRlcygiSVMgRElTVElOQ1QgRlJPTSBPTEQiKSwgImFycml2YWwgYWN0b3IgdHJpZ2dlciBkb2VzIG5vdCBwcm90ZWN0IGZ1dHVyZSBhY3RvciBjaGFuZ2VzIik7Cgpjb25zb2xlLmxvZygiQ0FTQSBTY2hvb2wgUGFzcyBBIHNvdXJjZSBjb250cmFjdCBzZWxmLXRlc3QgcGFzc2VkLiIpOwo=
'@

function Abort([string]$Message) {
  throw "ABORTED: $Message"
}

function Repo-Path([string]$RelativePath) {
  $native = $RelativePath.Replace('/', [IO.Path]::DirectorySeparatorChar)
  return Join-Path $script:RepoRoot $native
}

function Hash-Of([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    Abort "Required file is missing: $Path"
  }
  return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Assert-Hash([string]$RelativePath, [string]$ExpectedHash) {
  $actual = Hash-Of (Repo-Path $RelativePath)
  if ($actual -ne $ExpectedHash.ToLowerInvariant()) {
    Abort "Checksum drift: $RelativePath`nExpected: $ExpectedHash`nActual:   $actual"
  }
}

function Write-EmbeddedBytes([string]$RelativePath, [string]$Base64, [string]$ExpectedHash) {
  $bytes = [Convert]::FromBase64String(($Base64 -replace "\s", ""))
  $path = Repo-Path $RelativePath
  [IO.File]::WriteAllBytes($path, $bytes)
  Assert-Hash $RelativePath $ExpectedHash
}

function Git-Lines([string[]]$Arguments) {
  $stderrPath = [IO.Path]::GetTempFileName()
  $previousErrorActionPreference = $ErrorActionPreference
  $exitCode = $null
  $stdout = @()
  try {
    $ErrorActionPreference = "Continue"
    $stdout = @(& git -C $script:RepoRoot @Arguments 2> $stderrPath)
    $exitCode = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }

  $stderr = @()
  try {
    if (Test-Path -LiteralPath $stderrPath -PathType Leaf) {
      $stderr = @(Get-Content -LiteralPath $stderrPath -ErrorAction SilentlyContinue | ForEach-Object { [string]$_ })
    }
  }
  finally {
    Remove-Item -LiteralPath $stderrPath -Force -ErrorAction SilentlyContinue
  }

  if ($null -eq $exitCode) {
    Abort "git $($Arguments -join ' ') did not return an exit code."
  }
  if ($exitCode -ne 0) {
    $details = @()
    if ($stdout.Count -gt 0) { $details += "stdout:"; $details += $stdout }
    if ($stderr.Count -gt 0) { $details += "stderr:"; $details += $stderr }
    Abort "git $($Arguments -join ' ') failed with exit code $exitCode`n$($details -join [Environment]::NewLine)"
  }
  return @($stdout | ForEach-Object { [string]$_ })
}

function Git-Text([string[]]$Arguments) {
  return ((Git-Lines $Arguments) -join "`n").Trim()
}

function Invoke-NativeChecked([string]$Label, [scriptblock]$Command) {
  $previousErrorActionPreference = $ErrorActionPreference
  $exitCode = $null
  try {
    $ErrorActionPreference = "Continue"
    & $Command
    $exitCode = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }

  if ($null -eq $exitCode) {
    Abort "$Label did not return an exit code."
  }
  if ($exitCode -ne 0) {
    Abort "$Label failed with exit code $exitCode."
  }
}

function Migration-Directories {
  return @(
    Get-ChildItem -LiteralPath (Repo-Path "drizzle") -Directory |
      Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName "migration.sql") -PathType Leaf } |
      Sort-Object Name
  )
}

function Assert-SetEqual([string[]]$Actual, [string[]]$Expected, [string]$Label) {
  $a = @($Actual | Sort-Object -Unique)
  $e = @($Expected | Sort-Object -Unique)
  $delta = @(Compare-Object -ReferenceObject $e -DifferenceObject $a)
  if ($delta.Count -gt 0) {
    Abort "$Label mismatch.`nExpected:`n$($e -join [Environment]::NewLine)`nFound:`n$($a -join [Environment]::NewLine)"
  }
}

function Resolve-ScannerTrustPaths {
  $tracked = Git-Lines @("ls-files")
  $scannerMatches = New-Object System.Collections.Generic.List[string]
  $cssMatches = New-Object System.Collections.Generic.List[string]

  foreach ($relative in $tracked) {
    $path = Repo-Path $relative
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { continue }
    $hash = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($hash -eq $ScannerHash) { $scannerMatches.Add($relative) }
    if ($hash -eq $ScannerCssHash) { $cssMatches.Add($relative) }
  }

  if ($scannerMatches.Count -ne 1) {
    Abort "Locked Scanner source hash resolved to $($scannerMatches.Count) tracked files; expected exactly 1."
  }
  if ($cssMatches.Count -ne 1) {
    Abort "Locked Scanner CSS hash resolved to $($cssMatches.Count) tracked files; expected exactly 1."
  }

  return @{
    Scanner = $scannerMatches[0]
    ScannerCss = $cssMatches[0]
  }
}

function Write-ProbeScript([string]$Path) {
  $probe = @'
import { config } from "dotenv";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";

const repo = process.argv[2];
const expectedStage = Number(process.argv[3]);
const expectedHost = process.argv[4];

if (![28, 29, 30].includes(expectedStage)) {
  throw new Error(`Invalid expected stage: ${expectedStage}`);
}

config({ path: join(repo, ".env.local"), quiet: true });
config({ path: join(repo, ".env"), quiet: true });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not configured.");
}

const parsed = new URL(databaseUrl);
const actualHost = parsed.hostname.toLowerCase();
if (actualHost !== expectedHost.toLowerCase()) {
  throw new Error(`DEVELOPMENT HOST GUARD FAILED. Expected ${expectedHost}; found ${actualHost}.`);
}

const sql = neon(databaseUrl);

const migrationTable = await sql`
  select exists (
    select 1
    from information_schema.tables
    where table_schema = 'drizzle'
      and table_name = '__drizzle_migrations'
  ) as exists
`;
if (!migrationTable[0]?.exists) {
  throw new Error("drizzle.__drizzle_migrations does not exist.");
}

const rows = await sql`
  select id, hash, created_at
  from drizzle.__drizzle_migrations
  order by id
`;

const migrationDirs = readdirSync(join(repo, "drizzle"))
  .filter((name) => {
    const p = join(repo, "drizzle", name);
    return /^\d{14}_.+/.test(name)
      && statSync(p).isDirectory()
      && statSync(join(p, "migration.sql")).isFile();
  })
  .sort();

if (migrationDirs.length !== 30) {
  throw new Error(`Expected exactly 30 local migration folders; found ${migrationDirs.length}.`);
}

const local = migrationDirs.map((name) => {
  const migrationPath = join(repo, "drizzle", name, "migration.sql");
  const bytes = readFileSync(migrationPath);
  return {
    name,
    hash: createHash("sha256").update(bytes).digest("hex"),
  };
});

if (rows.length !== expectedStage) {
  throw new Error(`Development migration history count mismatch. Expected ${expectedStage}; found ${rows.length}.`);
}

const expectedHashes = new Set(local.slice(0, expectedStage).map((m) => m.hash));
const actualHashes = new Set(rows.map((r) => String(r.hash).toLowerCase()));

if (actualHashes.size !== expectedHashes.size) {
  throw new Error(`Development migration hash set cardinality mismatch at stage ${expectedStage}.`);
}
for (const hash of expectedHashes) {
  if (!actualHashes.has(hash)) {
    const migration = local.find((m) => m.hash === hash);
    throw new Error(`Development migration history is missing local migration ${migration?.name ?? hash}.`);
  }
}

const identityStatusValues = await sql`
  select e.enumlabel
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
    and t.typname = 'student_identity_card_status'
`;
const identityEventValues = await sql`
  select e.enumlabel
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
    and t.typname = 'student_identity_card_event_type'
`;
const lifecycleEventValues = await sql`
  select e.enumlabel
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
    and t.typname = 'school_attendance_lifecycle_event_type'
`;

const identityStatuses = new Set(identityStatusValues.map((r) => r.enumlabel));
const identityEvents = new Set(identityEventValues.map((r) => r.enumlabel));
const lifecycleEvents = new Set(lifecycleEventValues.map((r) => r.enumlabel));

const enumFlags = [
  identityStatuses.has("READY_FOR_ACTIVATION"),
  identityEvents.has("ACTIVATED"),
  lifecycleEvents.has("RESUME_SCHEDULED"),
  lifecycleEvents.has("RESUME_SCHEDULE_CANCELLED"),
];
const anyPassAEnum = enumFlags.some(Boolean);
const enumReady = enumFlags.every(Boolean);

const structural = await sql`
  select
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='school_attendance_lifecycles'
        and column_name='scheduled_resume_at'
    ) as scheduled_resume_at,
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='school_attendance_lifecycles'
        and column_name='scheduled_resume_by_membership_id'
    ) as scheduled_resume_by,
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='school_attendance_lifecycles'
        and column_name='scheduled_resume_reason'
    ) as scheduled_resume_reason,
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='school_attendance_lifecycle_events'
        and column_name='scheduled_for'
    ) as scheduled_for,
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='student_arrival_method_assignments'
        and column_name='assigned_by_internal_membership_id'
    ) as arrival_internal_actor,
    to_regclass('public.student_first_card_attendance_exceptions') is not null as first_card_table,
    to_regclass('public.student_supervised_late_arrivals') is not null as supervised_late_table,
    to_regclass('public.student_identity_cards_one_pending_activation_per_student_idx') is not null as pending_card_index
`;
const s = structural[0];
const structuralFlags = [
  s?.scheduled_resume_at,
  s?.scheduled_resume_by,
  s?.scheduled_resume_reason,
  s?.scheduled_for,
  s?.arrival_internal_actor,
  s?.first_card_table,
  s?.supervised_late_table,
  s?.pending_card_index,
].map(Boolean);
const anyStructural = structuralFlags.some(Boolean);
const structuralReady = structuralFlags.every(Boolean);

if (expectedStage === 28) {
  if (anyPassAEnum) {
    throw new Error("Pass A enum drift is already present while migration history says 28.");
  }
  if (anyStructural) {
    throw new Error("Pass A structural objects are already present while migration history says 28.");
  }
}

if (expectedStage === 29) {
  if (!enumReady) {
    throw new Error("Migration 29 is recorded but its enum expansion is incomplete.");
  }
  if (anyStructural) {
    throw new Error("Migration 30 structures exist while Development is expected at migration 29.");
  }
}

if (expectedStage === 30) {
  if (!enumReady) {
    throw new Error("Pass A enum expansion is incomplete after migration 30.");
  }
  if (!structuralReady) {
    throw new Error("Pass A structural migration is incomplete after migration 30.");
  }

  const statusDefault = await sql`
    select column_default
    from information_schema.columns
    where table_schema='public'
      and table_name='student_identity_cards'
      and column_name='status'
  `;
  if (!String(statusDefault[0]?.column_default ?? "").includes("READY_FOR_ACTIVATION")) {
    throw new Error("student_identity_cards.status default is not READY_FOR_ACTIVATION.");
  }

  const arrivalNullability = await sql`
    select is_nullable
    from information_schema.columns
    where table_schema='public'
      and table_name='student_arrival_method_assignments'
      and column_name='assigned_by_membership_id'
  `;
  if (arrivalNullability[0]?.is_nullable !== "YES") {
    throw new Error("student_arrival_method_assignments.assigned_by_membership_id is not nullable.");
  }

  const constraints = await sql`
    select c.conname
    from pg_constraint c
    join pg_namespace n on n.oid = c.connamespace
    where n.nspname = 'public'
      and c.conname in (
      'school_attendance_lifecycles_scheduled_resume_by_fk',
      'school_attendance_lifecycles_scheduled_resume_actor_check',
      'school_attendance_lifecycles_scheduled_resume_status_check',
      'school_attendance_lifecycles_scheduled_resume_reason_check',
      'student_arrival_method_assignments_internal_actor_fk',
      'student_arrival_method_assignments_actor_check',
      'student_first_card_attendance_exceptions_student_fk',
      'student_first_card_attendance_exceptions_card_fk',
      'student_first_card_attendance_exceptions_session_fk',
      'student_first_card_attendance_exceptions_record_fk',
      'student_first_card_attendance_exceptions_verifier_fk',
      'student_supervised_late_arrivals_branch_fk',
      'student_supervised_late_arrivals_student_fk',
      'student_supervised_late_arrivals_session_fk',
      'student_supervised_late_arrivals_record_fk',
      'student_supervised_late_arrivals_verifier_fk'
    )
  `;
  if (constraints.length !== 16) {
    throw new Error(`Pass A constraint set incomplete; expected 16, found ${constraints.length}.`);
  }

  const actorConstraint = await sql`
    select pg_get_constraintdef(c.oid) as definition
    from pg_constraint c
    join pg_class r on r.oid = c.conrelid
    join pg_namespace n on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'student_arrival_method_assignments'
      and c.conname = 'student_arrival_method_assignments_actor_check'
  `;
  if (actorConstraint.length !== 1) {
    throw new Error("Arrival actor compatibility constraint is missing.");
  }

  const actorTrigger = await sql`
    select pg_get_triggerdef(t.oid) as definition
    from pg_trigger t
    join pg_class r on r.oid = t.tgrelid
    join pg_namespace n on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'student_arrival_method_assignments'
      and t.tgname = 'student_arrival_method_assignments_actor_guard_trigger'
      and not t.tgisinternal
  `;
  if (actorTrigger.length !== 1) {
    throw new Error("Future arrival actor enforcement trigger is missing.");
  }
  const actorFunction = await sql`
    select pg_get_functiondef(p.oid) as definition
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'student_arrival_method_assignments_actor_guard'
  `;
  const actorFunctionDef = String(actorFunction[0]?.definition ?? "");
  if (!actorFunctionDef.includes("requires exactly one actor") || !actorFunctionDef.includes("TG_OP = 'INSERT'")) {
    throw new Error("Future arrival actor enforcement function is incomplete.");
  }

  const newRows = await sql`
    select
      (select count(*)::int from student_first_card_attendance_exceptions) as first_card_rows,
      (select count(*)::int from student_supervised_late_arrivals) as supervised_late_rows,
      (select count(*)::int from school_attendance_lifecycles where scheduled_resume_at is not null) as scheduled_resume_rows,
      (select count(*)::int from student_arrival_method_assignments where assigned_by_internal_membership_id is not null) as internal_actor_rows,
      (select count(*)::int from student_identity_cards where status = 'READY_FOR_ACTIVATION') as ready_for_activation_rows
  `;

  const counts = newRows[0];
  if (Number(counts?.first_card_rows ?? -1) !== 0) {
    throw new Error("Migration unexpectedly created first-card exception data.");
  }
  if (Number(counts?.supervised_late_rows ?? -1) !== 0) {
    throw new Error("Migration unexpectedly created supervised-late-arrival data.");
  }
  if (Number(counts?.scheduled_resume_rows ?? -1) !== 0) {
    throw new Error("Migration unexpectedly populated scheduled resume data.");
  }
  if (Number(counts?.internal_actor_rows ?? -1) !== 0) {
    throw new Error("Migration unexpectedly populated internal arrival actors.");
  }
  if (Number(counts?.ready_for_activation_rows ?? -1) !== 0) {
    throw new Error("Migration unexpectedly backfilled existing cards to READY_FOR_ACTIVATION.");
  }
}

const info = await sql`
  select current_database() as database_name, current_user as database_user
`;

console.log(`  Development host: ${actualHost}`);
console.log(`  database: ${info[0]?.database_name ?? "unknown"}`);
console.log(`  migration history: ${rows.length} / VERIFIED`);
if (expectedStage >= 29) console.log("  Pass A enum expansion: VERIFIED");
if (expectedStage >= 30) {
  console.log("  Pass A structural schema: VERIFIED");
  console.log("  existing application data: UNCHANGED BY MIGRATION / VERIFIED");
}
'@

  [IO.File]::WriteAllText(
    $Path,
    $probe,
    (New-Object System.Text.UTF8Encoding($false))
  )
}

function Invoke-DevelopmentProbe([string]$ProbePath, [int]$ExpectedStage) {
  Invoke-NativeChecked "Development read-only probe (stage $ExpectedStage)" {
    & node $ProbePath $script:RepoRoot ([string]$ExpectedStage) $ExpectedDevelopmentHost
  }
}

function New-IsolatedMigrationConfig(
  [string]$ConfigPath,
  [string]$MigrationOut
) {
  if ($MigrationOut.Contains('"')) {
    Abort "Temporary migration path contains an unsupported quote character."
  }
  $out = $MigrationOut -replace '\\', '/'
  $content = @"
import { config } from "dotenv";
import { defineConfig } from "drizzle-kit";

config({ path: ".env.local", quiet: true });
config({ path: ".env", quiet: true });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not configured.");
}

const parsed = new URL(databaseUrl);
if (parsed.hostname.toLowerCase() !== "$ExpectedDevelopmentHost") {
  throw new Error(
    "DEVELOPMENT HOST GUARD FAILED. Expected $ExpectedDevelopmentHost; found " + parsed.hostname
  );
}

export default defineConfig({
  out: "$out",
  dialect: "postgresql",
  migrations: {
    table: "__drizzle_migrations",
    schema: "drizzle",
  },
  dbCredentials: {
    url: databaseUrl,
  },
});
"@

  [IO.File]::WriteAllText(
    $ConfigPath,
    $content,
    (New-Object System.Text.UTF8Encoding($false))
  )
}

function Copy-MigrationSet([int]$Count, [string]$Destination) {
  New-Item -ItemType Directory -Path $Destination -Force | Out-Null
  $dirs = @(Migration-Directories)
  if ($dirs.Count -ne $ExpectedMigrationCount) {
    Abort "Expected $ExpectedMigrationCount migration folders, found $($dirs.Count)."
  }
  foreach ($dir in @($dirs | Select-Object -First $Count)) {
    Copy-Item -LiteralPath $dir.FullName -Destination (Join-Path $Destination $dir.Name) -Recurse -Force
  }
}

function Invoke-DrizzleMigrate([string]$Label, [string]$ConfigPath) {
  Invoke-NativeChecked $Label {
    & npx drizzle-kit migrate --config $ConfigPath
  }
}

function Write-ArrivalActorProfileScript([string]$Path) {
  $profile = @'
import { config } from "dotenv";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";

const repo = process.argv[2];
const expectedHost = process.argv[3];
config({ path: join(repo, ".env.local"), quiet: true });
config({ path: join(repo, ".env"), quiet: true });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("DATABASE_URL is not configured.");
const parsed = new URL(databaseUrl);
if (parsed.hostname.toLowerCase() !== expectedHost.toLowerCase()) {
  throw new Error(`DEVELOPMENT HOST GUARD FAILED. Expected ${expectedHost}; found ${parsed.hostname}.`);
}
const sql = neon(databaseUrl);
const column = await sql`
  select is_nullable
  from information_schema.columns
  where table_schema='public'
    and table_name='student_arrival_method_assignments'
    and column_name='assigned_by_membership_id'
`;
if (column.length !== 1) throw new Error("assigned_by_membership_id column was not found.");
const internalColumn = await sql`
  select exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='student_arrival_method_assignments'
      and column_name='assigned_by_internal_membership_id'
  ) as exists
`;
const hasInternal = Boolean(internalColumn[0]?.exists);
let counts;
if (hasInternal) {
  counts = await sql`
    select
      count(*)::int as total_rows,
      count(*) filter (
        where assigned_by_membership_id is null
          and assigned_by_internal_membership_id is null
      )::int as actorless_rows,
      count(*) filter (
        where assigned_by_membership_id is null
          and assigned_by_internal_membership_id is null
          and effective_to is null
      )::int as active_actorless_rows,
      count(*) filter (
        where assigned_by_membership_id is not null
          and assigned_by_internal_membership_id is not null
      )::int as dual_actor_rows,
      count(*) filter (
        where assigned_by_internal_membership_id is not null
      )::int as internal_actor_rows
    from student_arrival_method_assignments
  `;
} else {
  counts = await sql`
    select
      count(*)::int as total_rows,
      count(*) filter (
        where assigned_by_membership_id is null
      )::int as actorless_rows,
      count(*) filter (
        where assigned_by_membership_id is null
          and effective_to is null
      )::int as active_actorless_rows,
      0::int as dual_actor_rows,
      0::int as internal_actor_rows
    from student_arrival_method_assignments
  `;
}
console.log(JSON.stringify({
  isNullable: column[0]?.is_nullable ?? null,
  hasInternalActorColumn: hasInternal,
  ...counts[0],
}));
'@
  [IO.File]::WriteAllText(
    $Path,
    $profile,
    (New-Object System.Text.UTF8Encoding($false))
  )
}

function Invoke-ArrivalActorProfile([string]$Path) {
  $stderrPath = [IO.Path]::GetTempFileName()
  $previousErrorActionPreference = $ErrorActionPreference
  try {
    $ErrorActionPreference = "Continue"
    $stdout = @(& node $Path $script:RepoRoot $ExpectedDevelopmentHost 2> $stderrPath)
    $exitCode = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }
  $stderr = @()
  if (Test-Path -LiteralPath $stderrPath) {
    $stderr = @(Get-Content -LiteralPath $stderrPath -ErrorAction SilentlyContinue)
    Remove-Item -LiteralPath $stderrPath -Force -ErrorAction SilentlyContinue
  }
  if ($exitCode -ne 0) {
    Abort "Arrival actor read-only profile failed.`n$($stderr -join [Environment]::NewLine)"
  }
  $jsonLines = @($stdout | ForEach-Object { ([string]$_).Trim() } | Where-Object { $_ -match '^\{.*\}$' })
  if ($jsonLines.Count -ne 1) {
    Abort "Arrival actor profile returned ambiguous output.`n$($stdout -join [Environment]::NewLine)"
  }
  return ($jsonLines[0] | ConvertFrom-Json)
}

$script:SourcePatchApplied = $false
$script:DatabaseMigrationAttempted = $false
$script:SourceBackupDir = $null
$script:RecoveryBackupRoot = $null

try {
  Write-Host "CASA School - Pass A Development Migration 30 Recovery V2"
  Write-Host "Development database only."
  Write-Host "Recovery from the proven migration-30 actor-attribution constraint failure."
  Write-Host "Migration 29 must already be committed; migration 30 must be unapplied."
  Write-Host "No Staging, Production, AWS, or Scanner mutation."
  Write-Host ""

  if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Abort "git is not available." }
  if (-not (Get-Command npm -ErrorAction SilentlyContinue)) { Abort "npm is not available." }
  if (-not (Get-Command npx -ErrorAction SilentlyContinue)) { Abort "npx is not available." }
  if (-not (Get-Command node -ErrorAction SilentlyContinue)) { Abort "node is not available." }

  $resolved = (Resolve-Path -LiteralPath $RepoRoot).Path
  $top = Git-Text @("rev-parse", "--show-toplevel")
  $topResolved = (Resolve-Path -LiteralPath $top).Path
  if ($resolved.TrimEnd([char[]]"\/") -ne $topResolved.TrimEnd([char[]]"\/")) {
    Abort "Run this script from the CASA repository root."
  }
  $script:RepoRoot = $topResolved

  Write-Host "==> Re-proving exact green Pass A source state"
  $branch = Git-Text @("branch", "--show-current")
  $head = Git-Text @("rev-parse", "--short=7", "HEAD")
  if ($branch -ne $ExpectedBranch) { Abort "Expected branch $ExpectedBranch, found $branch." }
  if ($head -ne $ExpectedHead) { Abort "Expected HEAD $ExpectedHead, found $head." }

  Assert-Hash "package.json" $PackageJsonHash
  Assert-Hash "package-lock.json" $PackageLockHash
  Assert-Hash "drizzle.config.ts" $DrizzleConfigHash

  foreach ($relative in ($MigrationManifest.Keys | Sort-Object)) {
    Assert-Hash $relative ([string]$MigrationManifest[$relative])
  }
  $migration30Relative = "drizzle/$PassA30Folder/migration.sql"
  $selftestRelative = "scripts/pass-a-selftest.ts"
  foreach ($relative in ($PayloadManifest.Keys | Sort-Object)) {
    if ($relative -eq $migration30Relative -or $relative -eq $selftestRelative) { continue }
    Assert-Hash $relative ([string]$PayloadManifest[$relative])
  }

  $migration30CurrentHash = Hash-Of (Repo-Path $migration30Relative)
  $selftestCurrentHash = Hash-Of (Repo-Path $selftestRelative)
  if ($migration30CurrentHash -eq $PassA30OriginalHash -and $selftestCurrentHash -eq $PassASelftestOriginalHash) {
    $sourceNeedsRepair = $true
  }
  elseif ($migration30CurrentHash -eq $PassA30Hash -and $selftestCurrentHash -eq $PassASelftestHash) {
    $sourceNeedsRepair = $false
  }
  else {
    Abort "Migration-30 recovery source pair is in an unexpected state.`nMigration 30: $migration30CurrentHash`nPass A self-test: $selftestCurrentHash"
  }

  # From this point onward, the authoritative post-recovery hashes are required.
  $PayloadManifest[$migration30Relative] = $PassA30Hash
  $PayloadManifest[$selftestRelative] = $PassASelftestHash

  $migrationDirs = @(Migration-Directories)
  if ($migrationDirs.Count -ne $ExpectedMigrationCount) {
    Abort "Expected $ExpectedMigrationCount migration folders, found $($migrationDirs.Count)."
  }
  if ($migrationDirs[28].Name -ne $PassA29Folder -or $migrationDirs[29].Name -ne $PassA30Folder) {
    Abort "Migration 29/30 ordering drift."
  }

  $expectedModified = @(
    $PayloadManifest.Keys |
      Where-Object { $NewPaths -notcontains $_ } |
      Sort-Object
  )
  $actualModified = @(
    Git-Lines @("diff", "--name-only", "HEAD", "--") |
      Where-Object { $_ } |
      Sort-Object
  )
  Assert-SetEqual $actualModified $expectedModified "Tracked Pass A source drift"

  $actualProductUntracked = @(
    Git-Lines @("ls-files", "--others", "--exclude-standard") |
      Where-Object {
        $_ -like "src/*" -or
        $_ -like "scripts/*" -or
        $_ -like "drizzle/*"
      } |
      Sort-Object
  )
  Assert-SetEqual $actualProductUntracked @($NewPaths | Sort-Object) "Untracked Pass A product paths"

  [void](Git-Lines @("diff", "--check", "HEAD", "--"))

  $scanner = Resolve-ScannerTrustPaths
  Write-Host "  branch/head: $branch/$head"
  Write-Host "  Pass A payload baseline/recovery state: VERIFIED"
  Write-Host "  migrations: 30 / exact hashes verified"
  Write-Host "  Scanner: byte-for-byte locked"
  Write-Host "  git diff --check: passed"

  Write-Host ""
  Write-Host "==> Guardedly correcting unapplied migration 30 actor semantics"
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $backupRoot = Join-Path (Repo-Path ".casa-backups") "pass-a-m30-recovery-$stamp"
  $sourceBackupDir = Join-Path $backupRoot "source-before-recovery"
  New-Item -ItemType Directory -Path $sourceBackupDir -Force | Out-Null
  $script:RecoveryBackupRoot = $backupRoot
  $script:SourceBackupDir = $sourceBackupDir

  Copy-Item -LiteralPath (Repo-Path "drizzle/$PassA30Folder/migration.sql") -Destination (Join-Path $sourceBackupDir "migration30.before.sql") -Force
  Copy-Item -LiteralPath (Repo-Path "scripts/pass-a-selftest.ts") -Destination (Join-Path $sourceBackupDir "pass-a-selftest.before.ts") -Force

  if ($sourceNeedsRepair) {
    Write-EmbeddedBytes $migration30Relative $CorrectedMigration30Base64 $PassA30Hash
    Write-EmbeddedBytes $selftestRelative $CorrectedPassASelftestBase64 $PassASelftestHash
    $script:SourcePatchApplied = $true
    Write-Host "  source repair: APPLIED"
  }
  else {
    Assert-Hash $migration30Relative $PassA30Hash
    Assert-Hash $selftestRelative $PassASelftestHash
    Write-Host "  source repair: ALREADY PRESENT / VERIFIED"
  }

  [void](Git-Lines @("diff", "--check", "HEAD", "--"))
  Write-Host "  migration 30: legacy-unknown actors preserved; future exact-one actor trigger added"
  Write-Host "  Pass A self-test: recovery contract verified"
  Write-Host "  git diff --check: passed after repair"
  Write-Host "  backup: $sourceBackupDir"

  Write-Host ""
  Write-Host "==> Re-running source gates before any database mutation"
  Push-Location $script:RepoRoot
  try {
    Invoke-NativeChecked "npm run typecheck" { & npm run typecheck }
    Invoke-NativeChecked "npm run scanner:selftest" { & npm run scanner:selftest }
    Invoke-NativeChecked "npm run card:selftest" { & npm run card:selftest }
    Invoke-NativeChecked "Pass A source contract self-test" { & npx tsx scripts/pass-a-selftest.ts }
  }
  finally {
    Pop-Location
  }

  Copy-Item -LiteralPath (Repo-Path "drizzle/$PassA29Folder") -Destination (Join-Path $backupRoot $PassA29Folder) -Recurse -Force
  Copy-Item -LiteralPath (Repo-Path "drizzle/$PassA30Folder") -Destination (Join-Path $backupRoot $PassA30Folder) -Recurse -Force

  $probePath = Join-Path $backupRoot "pass-a-development-probe.mjs"
  Write-ProbeScript $probePath
  $arrivalProfilePath = Join-Path $backupRoot "pass-a-arrival-actor-profile.mjs"
  Write-ArrivalActorProfileScript $arrivalProfilePath

  Write-Host ""
  Write-Host "==> Read-only Development database authority probe"
  # Determine current safe state without displaying DATABASE_URL credentials.
  $stateProbePath = Join-Path $backupRoot "pass-a-state-probe.mjs"
  $stateProbe = @'
import { config } from "dotenv";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";

const repo = process.argv[2];
const expectedHost = process.argv[3];
config({ path: join(repo, ".env.local"), quiet: true });
config({ path: join(repo, ".env"), quiet: true });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("DATABASE_URL is not configured.");
const parsed = new URL(databaseUrl);
if (parsed.hostname.toLowerCase() !== expectedHost.toLowerCase()) {
  throw new Error(`DEVELOPMENT HOST GUARD FAILED. Expected ${expectedHost}; found ${parsed.hostname}.`);
}
const sql = neon(databaseUrl);
const rows = await sql`select hash from drizzle.__drizzle_migrations order by id`;
const hashes = rows.map((r) => String(r.hash).toLowerCase());
const h29 = "cb8d914ea1f6d54922778f7a08b7183c643cbebcc8f148b7b141daa021cf4b11";
const h30 = "6ca8172dacde212cb808f126a6c30449d2395a9da292da1df69b15b255793ed0";

let stage;
if (rows.length === 28 && !hashes.includes(h29) && !hashes.includes(h30)) stage = 28;
else if (rows.length === 29 && hashes.includes(h29) && !hashes.includes(h30)) stage = 29;
else if (rows.length === 30 && hashes.includes(h29) && hashes.includes(h30)) stage = 30;
else throw new Error(`Unexpected Development migration state: count=${rows.length}, passA29=${hashes.includes(h29)}, passA30=${hashes.includes(h30)}`);

console.log(stage);
'@
  [IO.File]::WriteAllText(
    $stateProbePath,
    $stateProbe,
    (New-Object System.Text.UTF8Encoding($false))
  )

  $stderrPath = [IO.Path]::GetTempFileName()
  $previousErrorActionPreference = $ErrorActionPreference
  try {
    $ErrorActionPreference = "Continue"
    $stateOutput = @(& node $stateProbePath $script:RepoRoot $ExpectedDevelopmentHost 2> $stderrPath)
    $stateExit = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }
  $stateErr = @()
  if (Test-Path -LiteralPath $stderrPath) {
    $stateErr = @(Get-Content -LiteralPath $stderrPath -ErrorAction SilentlyContinue)
    Remove-Item -LiteralPath $stderrPath -Force -ErrorAction SilentlyContinue
  }
  if ($stateExit -ne 0) {
    Abort "Development state probe failed.`n$($stateErr -join [Environment]::NewLine)"
  }
  $stageLines = @(
    $stateOutput |
      ForEach-Object { ([string]$_).Trim() } |
      Where-Object { $_ -match '^(28|29|30)$' }
  )
  if ($stageLines.Count -ne 1) {
    Abort "Development state probe returned an ambiguous stage.`nOutput:`n$($stateOutput -join [Environment]::NewLine)"
  }
  $currentStage = [int]$stageLines[0]
  Invoke-DevelopmentProbe $probePath $currentStage

  if ($currentStage -eq 30) {
    $alreadyProfile = Invoke-ArrivalActorProfile $arrivalProfilePath
    Write-Host "  arrival actor trigger state: VERIFIED"
    Write-Host ""
    Write-Host "PASS A DEVELOPMENT MIGRATION 30 ALREADY GREEN."
    Write-Host "  migrations applied: 30 / VERIFIED"
    Write-Host "  Development schema: PASS A COMPLETE"
    Write-Host "  actorless historical rows preserved: $($alreadyProfile.actorless_rows)"
    Write-Host "  Staging/Production mutation: NO"
    Write-Host "  AWS mutation: NO"
    Write-Host "  Scanner mutation: NO"
    exit 0
  }

  if ($currentStage -ne 29) {
    Abort "Migration-30 recovery requires Development to be at the proven migration-29 boundary; found stage $currentStage."
  }

  Write-Host ""
  Write-Host "==> Profiling the proven migration-30 failure condition (read-only)"
  $preArrivalProfile = Invoke-ArrivalActorProfile $arrivalProfilePath
  if ([bool]$preArrivalProfile.hasInternalActorColumn) {
    Abort "assigned_by_internal_membership_id already exists at migration stage 29."
  }
  $legacyActorlessCount = [int]$preArrivalProfile.actorless_rows
  if ($legacyActorlessCount -le 0) {
    Abort "Expected at least one legacy arrival assignment with unknown actor after the proven constraint failure; found 0."
  }
  Write-Host "  arrival assignments: $($preArrivalProfile.total_rows)"
  Write-Host "  legacy unknown-actor rows: $legacyActorlessCount"
  Write-Host "  active legacy unknown-actor rows: $($preArrivalProfile.active_actorless_rows)"
  Write-Host "  repair policy: preserve unknown history; enforce exact-one actor on new/future actor changes"

  $set29 = Join-Path $backupRoot "isolated-drizzle-through-29"
  $set30 = Join-Path $backupRoot "isolated-drizzle-through-30"
  $config29 = Join-Path $backupRoot "drizzle-pass-a-29.config.ts"
  $config30 = Join-Path $backupRoot "drizzle-pass-a-30.config.ts"

  Copy-MigrationSet 29 $set29
  Copy-MigrationSet 30 $set30
  New-IsolatedMigrationConfig $config29 $set29
  New-IsolatedMigrationConfig $config30 $set30

  Push-Location $script:RepoRoot
  try {
    if ($currentStage -eq 28) {
      Write-Host ""
      Write-Host "==> Applying Development migration 29 ONLY"
      Write-Host "  $PassA29Folder"
      try {
        Invoke-DrizzleMigrate "Development migration 29" $config29
      }
      catch {
        Write-Host ""
        Write-Host "==> Migration 29 failed; proving Development remained at migration 28"
        try { Invoke-DevelopmentProbe $probePath 28 } catch { Write-Host "  read-only recovery proof also failed: $($_.Exception.Message)" }
        throw
      }

      Write-Host ""
      Write-Host "==> Re-proving committed migration 29 before migration 30"
      Invoke-DevelopmentProbe $probePath 29
      $currentStage = 29
    }

    if ($currentStage -eq 29) {
      Write-Host ""
      Write-Host "==> Applying Development migration 30 ONLY"
      Write-Host "  $PassA30Folder"
      try {
        $script:DatabaseMigrationAttempted = $true
        Invoke-DrizzleMigrate "Development migration 30" $config30
      }
      catch {
        Write-Host ""
        Write-Host "==> Migration 30 failed; proving migration 29 remains the committed safe boundary"
        try { Invoke-DevelopmentProbe $probePath 29 } catch { Write-Host "  read-only recovery proof also failed: $($_.Exception.Message)" }
        throw
      }

      Write-Host ""
      Write-Host "==> Final read-only Development Pass A schema proof"
      Invoke-DevelopmentProbe $probePath 30
      $postArrivalProfile = Invoke-ArrivalActorProfile $arrivalProfilePath
      if ([int]$postArrivalProfile.total_rows -ne [int]$preArrivalProfile.total_rows) {
        Abort "Arrival assignment row count changed during migration 30."
      }
      if ([int]$postArrivalProfile.actorless_rows -ne $legacyActorlessCount) {
        Abort "Legacy unknown-actor row count changed during migration 30."
      }
      if ([int]$postArrivalProfile.internal_actor_rows -ne 0) {
        Abort "Migration 30 unexpectedly populated internal arrival actors."
      }
      if ([int]$postArrivalProfile.dual_actor_rows -ne 0) {
        Abort "Migration 30 created dual-attributed arrival rows."
      }
      Write-Host "  legacy unknown-actor rows preserved: $legacyActorlessCount / VERIFIED"
      Write-Host "  future exact-one actor trigger: VERIFIED"
      $currentStage = 30
    }
  }
  finally {
    Pop-Location
  }

  Assert-Hash $scanner.Scanner $ScannerHash
  Assert-Hash $scanner.ScannerCss $ScannerCssHash
  foreach ($relative in ($PayloadManifest.Keys | Sort-Object)) {
    Assert-Hash $relative ([string]$PayloadManifest[$relative])
  }

  Write-Host ""
  Write-Host "PASS A DEVELOPMENT MIGRATION 30 RECOVERY PASSED."
  Write-Host "  source authority: main/a7aa668 + exact Pass A postimages"
  Write-Host "  Development migrations: 30 / VERIFIED"
  Write-Host "  migration 29: PRE-EXISTING + VERIFIED"
  Write-Host "  migration 30: REPAIRED + APPLIED + COMMITTED"
  Write-Host "  Pass A schema invariants: VERIFIED"
  Write-Host "  historical unknown actor attribution fabricated: NO"
  Write-Host "  existing application row data mutated by recovery: NO"
  Write-Host "  Scanner mutation: NO"
  Write-Host "  AWS mutation: NO"
  Write-Host "  Staging mutation: NO"
  Write-Host "  Production mutation: NO"
  Write-Host "  evidence backup: $backupRoot"
  Write-Host ""
  Write-Host "Next: paste this complete output back into ChatGPT. Do not touch Staging yet."
}
catch {
  if ($script:SourcePatchApplied -and -not $script:DatabaseMigrationAttempted -and $script:SourceBackupDir) {
    try {
      Copy-Item -LiteralPath (Join-Path $script:SourceBackupDir "migration30.before.sql") -Destination (Repo-Path "drizzle/$PassA30Folder/migration.sql") -Force
      Copy-Item -LiteralPath (Join-Path $script:SourceBackupDir "pass-a-selftest.before.ts") -Destination (Repo-Path "scripts/pass-a-selftest.ts") -Force
      Write-Host ""
      Write-Host "==> Source recovery rolled back because no database migration was attempted"
      Write-Host "  migration 30 source restored"
      Write-Host "  Pass A self-test restored"
    }
    catch {
      Write-Host "  WARNING: automatic source restore failed: $($_.Exception.Message)"
    }
  }
  Write-Error $_
  exit 1
}
