"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type School = { id:string; name:string; slug:string; student_count:number; billing_contact_name:string|null; billing_email:string|null; billing_phone:string|null; default_tax_label:string; default_tax_rate_bps:number; invoice_due_days:number; service_rate_kobo:string|number; replacement_rate_kobo:string|number };
type Invoice = { id:string; school_id:string; school_name:string; invoice_number:string; status:string; display_status:string; bill_to_email:string|null; subtotal_kobo:string|number; tax_label:string; tax_rate_bps:number; tax_kobo:string|number; total_kobo:string|number; paid_kobo:string|number; balance_kobo:string|number; issued_on:string|null; due_on:string|null };
type Payment = { id:string; invoice_id:string; school_name:string; invoice_number:string; receipt_number:string; amount_kobo:string|number; payment_method:string; payment_reference:string|null; received_on:string };
type Expense = { id:string; expense_number:string; vendor:string; category:string; description:string; amount_kobo:string|number; tax_kobo:string|number; payment_method:string; incurred_on:string; school_name:string|null };
type Recurring = { id:string; name:string; vendor:string; category:string; amount_kobo:string|number; cadence:string; next_due_on:string; school_name:string|null; is_active:boolean };
type LedgerLine = { journal_entry_id:string; source_type:string; school_name:string|null; description:string; posted_on:string; account_code:string; account_name:string; account_type:string; debit_kobo:string|number; credit_kobo:string|number; memo:string|null };
type SchoolReport = { school_id:string; school_name:string; invoiced_kobo:string|number; collected_kobo:string|number; outstanding_kobo:string|number };
type Snapshot = { schools:School[]; invoices:Invoice[]; payments:Payment[]; expenses:Expense[]; recurringExpenses:Recurring[]; ledger:LedgerLine[]; schoolReport:SchoolReport[]; summary:{ invoicedKobo:number; collectedKobo:number; expensesKobo:number; outstandingKobo:number; taxOnIssuedKobo:number; netCashflowKobo:number } };
type Tab = "OVERVIEW"|"INVOICES"|"PAYMENTS"|"EXPENSES"|"SUBSCRIPTIONS"|"LEDGER"|"REPORTS";

const tabs:Array<[Tab,string]> = [["OVERVIEW","Cashflow"],["INVOICES","Invoices"],["PAYMENTS","Payments & receipts"],["EXPENSES","Expenses"],["SUBSCRIPTIONS","Subscriptions"],["LEDGER","Ledger"],["REPORTS","Reports"]];
const today=()=>new Date().toISOString().slice(0,10);
function moneyKobo(value:string|number){ return `NGN ${new Intl.NumberFormat("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)/100)}`; }
function day(value:string|null){ if(!value)return "-"; return new Date(`${value}T00:00:00`).toLocaleDateString("en-NG",{dateStyle:"medium"}); }

export default function FinanceWorkbench(){
  const [tab,setTab]=useState<Tab>("OVERVIEW"); const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [invoiceSchoolId,setInvoiceSchoolId]=useState(""); const [invoiceQuantity,setInvoiceQuantity]=useState(""); const [invoiceTax,setInvoiceTax]=useState(""); const [invoiceNotes,setInvoiceNotes]=useState(""); const [invoiceIssueOn,setInvoiceIssueOn]=useState(today()); const [invoiceDueOn,setInvoiceDueOn]=useState(""); const [otherDescription,setOtherDescription]=useState(""); const [otherAmount,setOtherAmount]=useState("");
  const [paymentInvoiceId,setPaymentInvoiceId]=useState(""); const [paymentAmount,setPaymentAmount]=useState(""); const [paymentMethod,setPaymentMethod]=useState("BANK_TRANSFER"); const [paymentReference,setPaymentReference]=useState(""); const [paymentDate,setPaymentDate]=useState(today());
  const [expenseVendor,setExpenseVendor]=useState(""); const [expenseCategory,setExpenseCategory]=useState(""); const [expenseDescription,setExpenseDescription]=useState(""); const [expenseAmount,setExpenseAmount]=useState(""); const [expenseTax,setExpenseTax]=useState(""); const [expenseSchoolId,setExpenseSchoolId]=useState(""); const [expenseMethod,setExpenseMethod]=useState("BANK_TRANSFER"); const [expenseReference,setExpenseReference]=useState(""); const [expenseDate,setExpenseDate]=useState(today());
  const [subscriptionName,setSubscriptionName]=useState(""); const [subscriptionVendor,setSubscriptionVendor]=useState(""); const [subscriptionCategory,setSubscriptionCategory]=useState(""); const [subscriptionAmount,setSubscriptionAmount]=useState(""); const [subscriptionCadence,setSubscriptionCadence]=useState("MONTHLY"); const [subscriptionDue,setSubscriptionDue]=useState(today()); const [subscriptionSchoolId,setSubscriptionSchoolId]=useState("");

  const hydrateDefaults=useCallback((body:Snapshot)=>{
    const first=body.schools[0];
    if(first&&!invoiceSchoolId){ setInvoiceSchoolId(first.id); setInvoiceQuantity(String(first.student_count)); setInvoiceTax(String(Number(first.default_tax_rate_bps)/100)); const due=new Date(`${today()}T00:00:00`); due.setDate(due.getDate()+Number(first.invoice_due_days)); setInvoiceDueOn(due.toISOString().slice(0,10)); }
    if(!paymentInvoiceId){ const unpaid=body.invoices.find(i=>i.status!=="DRAFT"&&i.status!=="VOID"&&Number(i.balance_kobo)>0); if(unpaid){ setPaymentInvoiceId(unpaid.id); setPaymentAmount(String(Number(unpaid.balance_kobo)/100)); } }
  },[invoiceSchoolId,paymentInvoiceId]);

  const load=useCallback(async()=>{ const response=await fetch("/api/internal/finance/workbench",{cache:"no-store"}); const body=(await response.json().catch(()=>({}))) as Snapshot|{message?:string}; if(!response.ok||!("summary" in body)) throw new Error("message" in body&&typeof body.message==="string"?body.message:"Could not load Finance operations."); setSnapshot(body); hydrateDefaults(body); },[hydrateDefaults]);

  useEffect(()=>{ let cancelled=false; void (async()=>{ try{ const response=await fetch("/api/internal/finance/workbench",{cache:"no-store"}); const body=(await response.json().catch(()=>({}))) as Snapshot|{message?:string}; if(cancelled)return; if(!response.ok||!("summary" in body)) throw new Error("message" in body&&typeof body.message==="string"?body.message:"Could not load Finance operations."); setSnapshot(body); hydrateDefaults(body); }catch(caught){ if(!cancelled)setError(caught instanceof Error?caught.message:"Could not load Finance operations."); }})(); return()=>{cancelled=true}; },[hydrateDefaults]);

  const selectedSchool=useMemo(()=>snapshot?.schools.find(s=>s.id===invoiceSchoolId)??null,[snapshot,invoiceSchoolId]);
  const selectedPaymentInvoice=useMemo(()=>snapshot?.invoices.find(i=>i.id===paymentInvoiceId)??null,[snapshot,paymentInvoiceId]);

  async function post(body:Record<string,unknown>){ setBusy(true); setError(""); setNotice(""); try{ const response=await fetch("/api/internal/finance/workbench",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const result=(await response.json().catch(()=>({}))) as {message?:string;[key:string]:unknown}; if(!response.ok)throw new Error(result.message??"Finance operation failed."); await load(); return result; } finally { setBusy(false); } }
  function chooseInvoiceSchool(id:string){ setInvoiceSchoolId(id); const school=snapshot?.schools.find(s=>s.id===id); if(!school)return; setInvoiceQuantity(String(school.student_count)); setInvoiceTax(String(Number(school.default_tax_rate_bps)/100)); const due=new Date(`${invoiceIssueOn}T00:00:00`); due.setDate(due.getDate()+Number(school.invoice_due_days)); setInvoiceDueOn(due.toISOString().slice(0,10)); }

  async function createInvoice(e:FormEvent){ e.preventDefault(); try{ if(!invoiceSchoolId)throw new Error("Select a school."); const lines:Array<Record<string,unknown>>=[{lineKind:"SERVICE_FEE",description:"CASA service fee",quantity:Number(invoiceQuantity)}]; if(otherDescription.trim()&&Number(otherAmount)>0)lines.push({lineKind:"OTHER",description:otherDescription.trim(),quantity:1,unitAmountNaira:Number(otherAmount)}); const result=await post({action:"CREATE_INVOICE",schoolId:invoiceSchoolId,issuedOn:invoiceIssueOn,dueOn:invoiceDueOn,taxRatePercent:Number(invoiceTax||0),notes:invoiceNotes.trim()||null,lines}); setNotice(`Draft ${String(result.invoiceNumber??"invoice")} created.`); setOtherDescription("");setOtherAmount("");setInvoiceNotes("");setTab("INVOICES"); }catch(caught){setError(caught instanceof Error?caught.message:"Invoice drafting failed.");} }
  async function issueInvoice(invoiceId:string){ try{ const result=await post({action:"ISSUE_AND_EMAIL_INVOICE",invoiceId}); setNotice(`Invoice issued. Email delivery: ${String(result.emailDelivery??"UNKNOWN").replaceAll("_"," ")}.`); }catch(caught){setError(caught instanceof Error?caught.message:"Invoice issue failed.");} }
  async function recordPayment(e:FormEvent){ e.preventDefault(); try{ const result=await post({action:"RECORD_PAYMENT",invoiceId:paymentInvoiceId,amountNaira:Number(paymentAmount),receivedOn:paymentDate,paymentMethod,paymentReference:paymentReference.trim()||null}); setNotice(`Payment recorded. Receipt ${String(result.receiptNumber??"")}. Email delivery: ${String(result.emailDelivery??"UNKNOWN").replaceAll("_"," ")}.`); setPaymentReference("");setTab("PAYMENTS"); }catch(caught){setError(caught instanceof Error?caught.message:"Payment recording failed.");} }
  async function createExpense(e:FormEvent){ e.preventDefault(); try{ const result=await post({action:"CREATE_EXPENSE",vendor:expenseVendor,category:expenseCategory,description:expenseDescription,amountNaira:Number(expenseAmount),taxNaira:Number(expenseTax||0),paymentMethod:expenseMethod,paymentReference:expenseReference.trim()||null,incurredOn:expenseDate,schoolId:expenseSchoolId||null}); setNotice(`Expense ${String(result.expenseNumber??"")} recorded.`); setExpenseVendor("");setExpenseCategory("");setExpenseDescription("");setExpenseAmount("");setExpenseTax("");setExpenseReference(""); }catch(caught){setError(caught instanceof Error?caught.message:"Expense recording failed.");} }
  async function createSubscription(e:FormEvent){ e.preventDefault(); try{ await post({action:"CREATE_RECURRING_EXPENSE",name:subscriptionName,vendor:subscriptionVendor,category:subscriptionCategory,amountNaira:Number(subscriptionAmount),cadence:subscriptionCadence,nextDueOn:subscriptionDue,schoolId:subscriptionSchoolId||null}); setNotice("Recurring expense saved.");setSubscriptionName("");setSubscriptionVendor("");setSubscriptionCategory("");setSubscriptionAmount(""); }catch(caught){setError(caught instanceof Error?caught.message:"Recurring expense creation failed.");} }

  if(!snapshot)return <section className="border-b border-black/15 bg-white px-5 py-8 sm:px-8 lg:px-10"><p className="text-sm text-black/55">Loading CASA Finance operations...</p>{error?<p className="mt-3 text-sm text-[#7e1d18]">{error}</p>:null}</section>;
  const activeInvoices=snapshot.invoices.filter(i=>i.status!=="DRAFT"&&i.status!=="VOID"&&Number(i.balance_kobo)>0);

  return <section className="border-b border-black/15 bg-[#f2f2ef]"><div className="px-5 py-6 sm:px-8 lg:px-10">
    <div className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button className={`border px-4 py-2 text-xs font-semibold uppercase tracking-[0.08em] ${tab===key?"border-black bg-black text-white":"border-black/20 bg-white text-black hover:border-black"}`} key={key} onClick={()=>{setTab(key);setError("");setNotice("")}} type="button">{label}</button>)}</div>
    {notice?<div className="mt-4 border border-[#145a3b]/30 bg-[#eaf4ed] px-4 py-3 text-sm text-[#145a3b]">{notice}</div>:null}
    {error?<div className="mt-4 border border-[#7e1d18]/30 bg-[#f6e8e6] px-4 py-3 text-sm text-[#7e1d18]">{error}</div>:null}

    {tab==="OVERVIEW"?<div className="mt-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Cash collected",snapshot.summary.collectedKobo],["Expenses",snapshot.summary.expensesKobo],["Net cashflow",snapshot.summary.netCashflowKobo],["Outstanding",snapshot.summary.outstandingKobo],["Tax on issued invoices",snapshot.summary.taxOnIssuedKobo]].map(([label,value])=><article className="border border-black bg-white p-4" key={String(label)}><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-black/45">{String(label)}</p><p className="mt-3 text-xl font-semibold tracking-[-0.03em]">{moneyKobo(Number(value))}</p></article>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="border border-black bg-white"><div className="border-b border-black p-4"><p className="casa-kicker text-black/40">Receivables</p><h3 className="mt-2 text-xl font-semibold">Outstanding invoices</h3></div><div className="divide-y divide-black/10">{activeInvoices.length===0?<p className="p-4 text-sm text-black/45">No outstanding invoices.</p>:activeInvoices.slice(0,8).map(i=><div className="flex items-center justify-between gap-4 p-4" key={i.id}><div className="min-w-0"><p className="truncate text-sm font-semibold">{i.school_name}</p><p className="mt-1 font-mono text-[9px] uppercase text-black/40">{i.invoice_number} - {i.display_status}</p></div><p className="font-mono text-xs font-semibold">{moneyKobo(i.balance_kobo)}</p></div>)}</div></section><section className="border border-black bg-white"><div className="border-b border-black p-4"><p className="casa-kicker text-black/40">Upcoming obligations</p><h3 className="mt-2 text-xl font-semibold">Recurring expenses</h3></div><div className="divide-y divide-black/10">{snapshot.recurringExpenses.length===0?<p className="p-4 text-sm text-black/45">No recurring expenses recorded.</p>:snapshot.recurringExpenses.slice(0,8).map(item=><div className="flex items-center justify-between gap-4 p-4" key={item.id}><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="mt-1 font-mono text-[9px] uppercase text-black/40">{item.vendor} - due {day(item.next_due_on)}</p></div><p className="font-mono text-xs font-semibold">{moneyKobo(item.amount_kobo)}</p></div>)}</div></section></div></div>:null}

    {tab==="INVOICES"?<div className="mt-6 grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><form className="border border-black bg-white p-5" onSubmit={createInvoice}><p className="casa-kicker text-black/40">Invoice drafter</p><h3 className="mt-2 text-2xl font-semibold">Create CASA invoice</h3><label className="casa-label mt-5"><span>School</span><select className="casa-field" value={invoiceSchoolId} onChange={e=>chooseInvoiceSchool(e.target.value)}>{snapshot.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{selectedSchool?<div className="mt-4 border border-black/15 bg-black/[0.02] p-4 text-xs leading-5 text-black/60">Negotiated service rate: <strong>{moneyKobo(selectedSchool.service_rate_kobo)}</strong> per student / term.<br/>Billing email: <strong>{selectedSchool.billing_email||"Not configured"}</strong></div>:null}<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Students / quantity</span><input className="casa-field" min="1" step="1" type="number" value={invoiceQuantity} onChange={e=>setInvoiceQuantity(e.target.value)} required/></label><label className="casa-label"><span>Tax rate (%)</span><input className="casa-field" min="0" max="100" step="0.01" type="number" value={invoiceTax} onChange={e=>setInvoiceTax(e.target.value)}/></label></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Issue date</span><input className="casa-field" type="date" value={invoiceIssueOn} onChange={e=>setInvoiceIssueOn(e.target.value)} required/></label><label className="casa-label"><span>Due date</span><input className="casa-field" type="date" value={invoiceDueOn} onChange={e=>setInvoiceDueOn(e.target.value)} required/></label></div><div className="mt-5 border-t border-black/15 pt-5"><p className="text-sm font-semibold">Optional extra item</p><label className="casa-label mt-3"><span>Description</span><input className="casa-field" value={otherDescription} onChange={e=>setOtherDescription(e.target.value)} placeholder="e.g. Implementation support"/></label><label className="casa-label mt-3"><span>Amount (NGN)</span><input className="casa-field" min="0" step="0.01" type="number" value={otherAmount} onChange={e=>setOtherAmount(e.target.value)}/></label></div><label className="casa-label mt-4"><span>Invoice note</span><textarea className="casa-field min-h-24" value={invoiceNotes} onChange={e=>setInvoiceNotes(e.target.value)}/></label><button className="casa-button-primary mt-5" disabled={busy}>{busy?"Saving...":"Create draft invoice"}</button></form>
      <section className="border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Invoice register</p><h3 className="mt-2 text-2xl font-semibold">Drafted and issued invoices</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-black bg-black/[0.03] font-mono text-[9px] uppercase tracking-[0.1em] text-black/50"><tr><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">School</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Due</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Balance</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-black/10">{snapshot.invoices.map(i=><tr key={i.id}><td className="px-4 py-3 font-mono text-xs">{i.invoice_number}</td><td className="px-4 py-3 font-medium">{i.school_name}</td><td className="px-4 py-3">{i.display_status.replaceAll("_"," ")}</td><td className="px-4 py-3">{day(i.due_on)}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(i.total_kobo)}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(i.balance_kobo)}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-2"><a className="casa-button text-xs" href={`/internal/finance/invoices/${i.id}`} rel="noreferrer" target="_blank">View / print</a>{i.status!=="PAID"&&i.status!=="VOID"?<button className="casa-button-primary text-xs" disabled={busy} onClick={()=>void issueInvoice(i.id)} type="button">{i.status==="DRAFT"?"Issue & email":"Email again"}</button>:null}</div></td></tr>)}{snapshot.invoices.length===0?<tr><td className="px-4 py-8 text-center text-black/45" colSpan={7}>No invoices yet.</td></tr>:null}</tbody></table></div></section></div>:null}

    {tab==="PAYMENTS"?<div className="mt-6 grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><form className="border border-black bg-white p-5" onSubmit={recordPayment}><p className="casa-kicker text-black/40">Payment recorder</p><h3 className="mt-2 text-2xl font-semibold">Record invoice payment</h3><label className="casa-label mt-5"><span>Invoice</span><select className="casa-field" value={paymentInvoiceId} onChange={e=>{const id=e.target.value;setPaymentInvoiceId(id);const invoice=snapshot.invoices.find(i=>i.id===id);setPaymentAmount(invoice?String(Number(invoice.balance_kobo)/100):"")}} required><option value="">Select invoice</option>{activeInvoices.map(i=><option key={i.id} value={i.id}>{i.invoice_number} - {i.school_name} - {moneyKobo(i.balance_kobo)}</option>)}</select></label>{selectedPaymentInvoice?<div className="mt-4 border border-black/15 bg-black/[0.02] p-4 text-xs leading-5 text-black/60">Remaining balance: <strong>{moneyKobo(selectedPaymentInvoice.balance_kobo)}</strong></div>:null}<label className="casa-label mt-4"><span>Amount received (NGN)</span><input className="casa-field" min="0.01" step="0.01" type="number" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Payment date</span><input className="casa-field" type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} required/></label><label className="casa-label"><span>Method</span><select className="casa-field" value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></select></label></div><label className="casa-label mt-4"><span>Payment reference</span><input className="casa-field" value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/></label><button className="casa-button-primary mt-5" disabled={busy||!paymentInvoiceId}>{busy?"Recording...":"Record payment & generate receipt"}</button></form>
      <section className="border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Receipt register</p><h3 className="mt-2 text-2xl font-semibold">Payments and receipts</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-black bg-black/[0.03] font-mono text-[9px] uppercase tracking-[0.1em] text-black/50"><tr><th className="px-4 py-3">Receipt</th><th className="px-4 py-3">School</th><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Method</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3">Receipt</th></tr></thead><tbody className="divide-y divide-black/10">{snapshot.payments.map(p=><tr key={p.id}><td className="px-4 py-3 font-mono text-xs">{p.receipt_number}</td><td className="px-4 py-3">{p.school_name}</td><td className="px-4 py-3 font-mono text-xs">{p.invoice_number}</td><td className="px-4 py-3">{day(p.received_on)}</td><td className="px-4 py-3">{p.payment_method.replaceAll("_"," ")}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(p.amount_kobo)}</td><td className="px-4 py-3"><a className="casa-button text-xs" href={`/internal/finance/receipts/${p.id}`} rel="noreferrer" target="_blank">View / print</a></td></tr>)}{snapshot.payments.length===0?<tr><td className="px-4 py-8 text-center text-black/45" colSpan={7}>No payments recorded yet.</td></tr>:null}</tbody></table></div></section></div>:null}

    {tab==="EXPENSES"?<div className="mt-6 grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><form className="border border-black bg-white p-5" onSubmit={createExpense}><p className="casa-kicker text-black/40">Expense tracking</p><h3 className="mt-2 text-2xl font-semibold">Record CASA expense</h3><label className="casa-label mt-5"><span>Vendor</span><input className="casa-field" value={expenseVendor} onChange={e=>setExpenseVendor(e.target.value)} placeholder="e.g. Vercel, Neon, AWS" required/></label><label className="casa-label mt-4"><span>Category</span><input className="casa-field" value={expenseCategory} onChange={e=>setExpenseCategory(e.target.value)} placeholder="e.g. Cloud infrastructure" required/></label><label className="casa-label mt-4"><span>Description</span><textarea className="casa-field min-h-24" value={expenseDescription} onChange={e=>setExpenseDescription(e.target.value)} required/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Total amount (NGN)</span><input className="casa-field" min="0.01" step="0.01" type="number" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)} required/></label><label className="casa-label"><span>Tax included (NGN)</span><input className="casa-field" min="0" step="0.01" type="number" value={expenseTax} onChange={e=>setExpenseTax(e.target.value)}/></label></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Date</span><input className="casa-field" type="date" value={expenseDate} onChange={e=>setExpenseDate(e.target.value)} required/></label><label className="casa-label"><span>Method</span><select className="casa-field" value={expenseMethod} onChange={e=>setExpenseMethod(e.target.value)}><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></select></label></div><label className="casa-label mt-4"><span>Related school (optional)</span><select className="casa-field" value={expenseSchoolId} onChange={e=>setExpenseSchoolId(e.target.value)}><option value="">CASA general expense</option>{snapshot.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="casa-label mt-4"><span>Reference</span><input className="casa-field" value={expenseReference} onChange={e=>setExpenseReference(e.target.value)}/></label><button className="casa-button-primary mt-5" disabled={busy}>{busy?"Recording...":"Record expense"}</button></form>
      <section className="border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Expense register</p><h3 className="mt-2 text-2xl font-semibold">Recorded expenses</h3></div><div className="divide-y divide-black/10">{snapshot.expenses.map(e=><div className="grid gap-3 p-4 sm:grid-cols-[1fr_auto]" key={e.id}><div><p className="font-semibold">{e.vendor} - {e.description}</p><p className="mt-1 font-mono text-[9px] uppercase text-black/40">{e.expense_number} - {e.category} - {day(e.incurred_on)}{e.school_name?` - ${e.school_name}`:""}</p></div><p className="font-mono text-xs font-semibold">{moneyKobo(e.amount_kobo)}</p></div>)}{snapshot.expenses.length===0?<p className="p-5 text-sm text-black/45">No expenses recorded yet.</p>:null}</div></section></div>:null}

    {tab==="SUBSCRIPTIONS"?<div className="mt-6 grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><form className="border border-black bg-white p-5" onSubmit={createSubscription}><p className="casa-kicker text-black/40">Subscription & recurring expenses</p><h3 className="mt-2 text-2xl font-semibold">Track recurring obligation</h3><label className="casa-label mt-5"><span>Name</span><input className="casa-field" value={subscriptionName} onChange={e=>setSubscriptionName(e.target.value)} placeholder="e.g. Production Vercel" required/></label><label className="casa-label mt-4"><span>Vendor</span><input className="casa-field" value={subscriptionVendor} onChange={e=>setSubscriptionVendor(e.target.value)} required/></label><label className="casa-label mt-4"><span>Category</span><input className="casa-field" value={subscriptionCategory} onChange={e=>setSubscriptionCategory(e.target.value)} required/></label><label className="casa-label mt-4"><span>Amount per cycle (NGN)</span><input className="casa-field" min="0.01" step="0.01" type="number" value={subscriptionAmount} onChange={e=>setSubscriptionAmount(e.target.value)} required/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="casa-label"><span>Cadence</span><select className="casa-field" value={subscriptionCadence} onChange={e=>setSubscriptionCadence(e.target.value)}><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="SEMI_ANNUAL">Semi annual</option><option value="ANNUAL">Annual</option></select></label><label className="casa-label"><span>Next due date</span><input className="casa-field" type="date" value={subscriptionDue} onChange={e=>setSubscriptionDue(e.target.value)} required/></label></div><label className="casa-label mt-4"><span>Related school (optional)</span><select className="casa-field" value={subscriptionSchoolId} onChange={e=>setSubscriptionSchoolId(e.target.value)}><option value="">CASA general obligation</option>{snapshot.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="casa-button-primary mt-5" disabled={busy}>{busy?"Saving...":"Save recurring expense"}</button></form>
      <section className="border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Obligation register</p><h3 className="mt-2 text-2xl font-semibold">Upcoming subscriptions</h3></div><div className="divide-y divide-black/10">{snapshot.recurringExpenses.map(r=><div className="grid gap-3 p-4 sm:grid-cols-[1fr_auto]" key={r.id}><div><p className="font-semibold">{r.name}</p><p className="mt-1 font-mono text-[9px] uppercase text-black/40">{r.vendor} - {r.category} - {r.cadence} - due {day(r.next_due_on)}{r.school_name?` - ${r.school_name}`:""}</p></div><p className="font-mono text-xs font-semibold">{moneyKobo(r.amount_kobo)}</p></div>)}{snapshot.recurringExpenses.length===0?<p className="p-5 text-sm text-black/45">No recurring expenses recorded yet.</p>:null}</div></section></div>:null}

    {tab==="LEDGER"?<section className="mt-6 border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Double-entry ledger</p><h3 className="mt-2 text-2xl font-semibold">System-generated journal</h3><p className="mt-2 max-w-3xl text-xs leading-5 text-black/45">Invoice issuing, payment recording, and expense recording create these entries automatically. Super Admins do not manually balance operational transactions.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-black bg-black/[0.03] font-mono text-[9px] uppercase tracking-[0.1em] text-black/50"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Account</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th></tr></thead><tbody className="divide-y divide-black/10">{snapshot.ledger.map((l,index)=><tr key={`${l.journal_entry_id}-${l.account_code}-${index}`}><td className="px-4 py-3">{day(l.posted_on)}</td><td className="px-4 py-3 font-mono text-[10px]">{l.source_type.replaceAll("_"," ")}</td><td className="px-4 py-3">{l.description}{l.school_name?<span className="block text-[10px] text-black/40">{l.school_name}</span>:null}</td><td className="px-4 py-3">{l.account_code} - {l.account_name}</td><td className="px-4 py-3 text-right font-mono text-xs">{Number(l.debit_kobo)>0?moneyKobo(l.debit_kobo):"-"}</td><td className="px-4 py-3 text-right font-mono text-xs">{Number(l.credit_kobo)>0?moneyKobo(l.credit_kobo):"-"}</td></tr>)}{snapshot.ledger.length===0?<tr><td className="px-4 py-8 text-center text-black/45" colSpan={6}>Ledger entries appear after an invoice is issued, payment is recorded, or expense is recorded.</td></tr>:null}</tbody></table></div></section>:null}

    {tab==="REPORTS"?<div className="mt-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Issued invoice value",snapshot.summary.invoicedKobo],["Cash collected",snapshot.summary.collectedKobo],["Operating expenses",snapshot.summary.expensesKobo],["Net cashflow",snapshot.summary.netCashflowKobo]].map(([label,value])=><article className="border border-black bg-white p-4" key={String(label)}><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-black/45">{String(label)}</p><p className="mt-3 text-xl font-semibold">{moneyKobo(Number(value))}</p></article>)}</div><section className="mt-5 border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">School financial report</p><h3 className="mt-2 text-2xl font-semibold">Invoiced, collected and outstanding</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-black bg-black/[0.03] font-mono text-[9px] uppercase tracking-[0.1em] text-black/50"><tr><th className="px-4 py-3">School</th><th className="px-4 py-3 text-right">Invoiced</th><th className="px-4 py-3 text-right">Collected</th><th className="px-4 py-3 text-right">Outstanding</th></tr></thead><tbody className="divide-y divide-black/10">{snapshot.schoolReport.map(r=><tr key={r.school_id}><td className="px-4 py-3 font-medium">{r.school_name}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(r.invoiced_kobo)}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(r.collected_kobo)}</td><td className="px-4 py-3 text-right font-mono text-xs">{moneyKobo(r.outstanding_kobo)}</td></tr>)}</tbody></table></div></section></div>:null}
  </div></section>;
}
