import { randomUUID } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { desc, sql } from "drizzle-orm";
import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { getDatabaseUrl } from "@/config/env";
import { getDb } from "@/db";
import { studentCardTemplates } from "@/db/schema";
import { requireCasaCapability } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse,casaInternalNoStoreHeaders } from "@/server/internal/http";
import { cardObjectExists } from "@/server/card-production/storage";
import { cardTemplateLayoutSchema } from "@/server/card-production/template-layout";
const schema=z.object({schoolId:z.string().uuid(),versionLabel:z.string().trim().min(1).max(80),frontSourceKey:z.string().min(1),backSourceKey:z.string().min(1),layout:cardTemplateLayoutSchema,activate:z.boolean().default(false)});
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function GET(){try{await requireCasaCapability("MASTER_TEMPLATE_ADMIN");const db=getDb();const templates=await db.select({id:studentCardTemplates.id,schoolId:studentCardTemplates.schoolId,versionLabel:studentCardTemplates.versionLabel,status:studentCardTemplates.status,layout:studentCardTemplates.layout,createdAt:studentCardTemplates.createdAt}).from(studentCardTemplates).orderBy(desc(studentCardTemplates.createdAt));return NextResponse.json({templates},{headers:casaInternalNoStoreHeaders})}catch(e){const r=casaInternalAuthErrorResponse(e);if(r)return r;throw e}}
export async function POST(request:NextRequest){try{const access=await requireCasaCapability("MASTER_TEMPLATE_ADMIN");const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the card template fields."},{status:400,headers:casaInternalNoStoreHeaders});const d=parsed.data;if([...d.layout.frontText,...d.layout.backText].some(x=>x.source==="CLASS"||x.source==="ACADEMIC_SESSION"))return NextResponse.json({message:"Class and Academic Session are digital-only and cannot be printed on the physical card."},{status:409,headers:casaInternalNoStoreHeaders});const ok=await Promise.all([cardObjectExists(d.frontSourceKey),cardObjectExists(d.backSourceKey)]);if(!ok.every(Boolean))return NextResponse.json({message:"Both uploaded card sides must exist."},{status:409,headers:casaInternalNoStoreHeaders});const db=getDb();const duplicate=rowsOf<{id:string}>(await db.execute(sql`select id from student_card_templates where school_id=${d.schoolId}::uuid and version_label=${d.versionLabel} limit 1`))[0];if(duplicate)return NextResponse.json({message:"That internal template version already exists for this school. Save the edit again to create the next revision."},{status:409,headers:casaInternalNoStoreHeaders});const templateId=randomUUID();const layout=JSON.stringify(d.layout);const metadata=JSON.stringify({versionLabel:d.versionLabel,activated:d.activate});const client=neon(getDatabaseUrl());if(d.activate){await client.transaction([
 client`update student_card_templates set status='RETIRED',activated_at=coalesce(activated_at,now()),retired_at=now(),updated_at=now() where school_id=${d.schoolId}::uuid and status='ACTIVE'`,
 client`insert into student_card_templates(id,school_id,version_label,status,front_source_key,back_source_key,layout,activated_at,retired_at,created_at,updated_at) values(${templateId}::uuid,${d.schoolId}::uuid,${d.versionLabel},'ACTIVE',${d.frontSourceKey},${d.backSourceKey},${layout}::jsonb,now(),null,now(),now())`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${d.schoolId}::uuid,'MASTER_CARD_TEMPLATE_CREATED_AND_ACTIVATED','CARD_TEMPLATE',${templateId}::uuid,${metadata}::jsonb,now())`
]);}else{await client.transaction([
 client`insert into student_card_templates(id,school_id,version_label,status,front_source_key,back_source_key,layout,activated_at,retired_at,created_at,updated_at) values(${templateId}::uuid,${d.schoolId}::uuid,${d.versionLabel},'DRAFT',${d.frontSourceKey},${d.backSourceKey},${layout}::jsonb,null,null,now(),now())`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${d.schoolId}::uuid,'MASTER_CARD_TEMPLATE_CREATED','CARD_TEMPLATE',${templateId}::uuid,${metadata}::jsonb,now())`
]);}return NextResponse.json({template:{id:templateId,schoolId:d.schoolId,versionLabel:d.versionLabel,status:d.activate?"ACTIVE":"DRAFT"}},{status:201,headers:casaInternalNoStoreHeaders})}catch(e){const r=casaInternalAuthErrorResponse(e);if(r)return r;console.error("Card template creation failed",e);return NextResponse.json({message:"Card template creation failed."},{status:500,headers:casaInternalNoStoreHeaders})}}
