import { createHash, randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { getDb } from "@/db";
import { AuthRequiredError, SchoolAccessDeniedError, requireSchoolRole } from "@/server/auth/authorization";
import { sendAccountAccessEmail } from "@/server/messaging/account-access-email";
export const dynamic="force-dynamic";
const noStore={"Cache-Control":"no-store"};
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function POST(request:NextRequest,{params}:{params:Promise<{slug:string;membershipId:string}>}){const{slug,membershipId}=await params;try{const access=await requireSchoolRole(slug,["OWNER","ADMIN"]);const db=getDb();const target=rowsOf<{user_id:string;full_name:string;email:string|null;roles:string[]}>(await db.execute(sql`select m.user_id,u.full_name,u.email,coalesce(array_agg(r.role::text) filter(where r.role is not null),array[]::text[]) roles from school_memberships m join users u on u.id=m.user_id left join school_membership_roles r on r.school_id=m.school_id and r.membership_id=m.id where m.school_id=${access.school.id}::uuid and m.id=${membershipId}::uuid and m.status='ACTIVE' group by m.user_id,u.full_name,u.email limit 1`))[0];if(!target)return NextResponse.json({message:"Active school account not found."},{status:404,headers:noStore});if(target.roles.includes("OWNER"))return NextResponse.json({message:"School Owner password recovery is controlled by CASA Super Admin."},{status:403,headers:noStore});if(target.roles.includes("ADMIN")&&!access.roles.includes("OWNER"))return NextResponse.json({message:"Only the School Owner can create a recovery link for a School Admin."},{status:403,headers:noStore});const raw=randomBytes(32).toString("base64url");const hash=createHash("sha256").update(raw).digest("hex");const expiresAt=new Date(Date.now()+24*60*60*1000);await db.execute(sql`update casa_account_setup_tokens set used_at=now() where user_id=${target.user_id}::uuid and used_at is null`);await db.execute(sql`insert into casa_account_setup_tokens(user_id,token_hash,purpose,created_by_internal_membership_id,expires_at) values(${target.user_id}::uuid,${hash},'SCHOOL_OWNER',null,${expiresAt.toISOString()}::timestamptz)`);const origin=new URL(request.url).origin;const setupUrl=`${origin}/account/setup?token=${encodeURIComponent(raw)}`;const emailDelivery=await sendAccountAccessEmail({email:target.email,recipientName:target.full_name,organizationName:access.school.name,actionLabel:"Recover CASA password",actionUrl:setupUrl,expiresAt,context:`${access.school.name} created a private CASA password recovery link for your school account.`});return NextResponse.json({emailDelivery,setup:{url:setupUrl,expiresAt:expiresAt.toISOString()}},{headers:noStore})}catch(error){if(error instanceof AuthRequiredError)return NextResponse.json({message:"Authentication required."},{status:401,headers:noStore});if(error instanceof SchoolAccessDeniedError)return NextResponse.json({message:"Owner or Admin access required."},{status:403,headers:noStore});console.error("School password recovery link failed",error);return NextResponse.json({message:"Recovery link could not be created."},{status:500,headers:noStore})}}
