import { createHash, randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { getDb } from "@/db";
import { requireCasaSuperAdmin } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse, casaInternalNoStoreHeaders } from "@/server/internal/http";
import { writeCasaInternalAudit } from "@/server/internal/onboarding";
export const dynamic="force-dynamic";
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function POST(request:NextRequest,{params}:{params:Promise<{schoolId:string}>}){try{const access=await requireCasaSuperAdmin();const{schoolId}=await params;const db=getDb();const owners=rowsOf<{membership_id:string;user_id:string;full_name:string;email:string|null}>(await db.execute(sql`select m.id membership_id,m.user_id,u.full_name,u.email from school_memberships m join school_membership_roles r on r.school_id=m.school_id and r.membership_id=m.id join users u on u.id=m.user_id where m.school_id=${schoolId}::uuid and m.status='ACTIVE' and r.role='OWNER' order by u.full_name`));if(owners.length!==1)return NextResponse.json({message:owners.length===0?"No active School Owner account was found.":"More than one active School Owner exists. Resolve ownership before creating a recovery link."},{status:409,headers:casaInternalNoStoreHeaders});const target=owners[0];const raw=randomBytes(32).toString("base64url");const hash=createHash("sha256").update(raw).digest("hex");const expiresAt=new Date(Date.now()+24*60*60*1000);await db.execute(sql`update casa_account_setup_tokens set used_at=now() where user_id=${target.user_id}::uuid and used_at is null`);await db.execute(sql`insert into casa_account_setup_tokens(user_id,token_hash,purpose,created_by_internal_membership_id,expires_at) values(${target.user_id}::uuid,${hash},'SCHOOL_OWNER',${access.membership.id}::uuid,${expiresAt.toISOString()}::timestamptz)`);await writeCasaInternalAudit({access,schoolId,action:"SCHOOL_OWNER_RECOVERY_LINK_CREATED",subjectType:"SCHOOL_MEMBERSHIP",subjectId:target.membership_id,metadata:{targetUserId:target.user_id,targetEmail:target.email}});const origin=new URL(request.url).origin;return NextResponse.json({setup:{url:`${origin}/account/setup?token=${encodeURIComponent(raw)}`,expiresAt:expiresAt.toISOString()}},{headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;console.error("School Owner recovery link failed",error);return NextResponse.json({message:"CASA could not create the School Owner recovery link."},{status:500,headers:casaInternalNoStoreHeaders})}}
