import { NextRequest, NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { requireCasaSuperAdmin } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse, casaInternalNoStoreHeaders } from "@/server/internal/http";
import { writeCasaInternalAudit } from "@/server/internal/onboarding";
export const dynamic="force-dynamic";
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
const bodySchema=z.object({userId:z.string().uuid(),role:z.enum(["CASA_SUPER_ADMIN","CASA_TEAM"]),status:z.enum(["ACTIVE","SUSPENDED"]).default("ACTIVE")});
export async function GET(){try{await requireCasaSuperAdmin();const result=await getDb().execute(sql`select m.id,m.user_id,u.full_name,u.email,u.phone,m.role,m.status,m.created_at,m.updated_at,(select count(*)::int from casa_internal_school_assignments a where a.membership_id=m.id and a.status='ACTIVE') as assigned_school_count from casa_internal_memberships m join users u on u.id=m.user_id order by u.full_name asc,m.created_at asc`);return NextResponse.json({memberships:rowsOf(result)},{headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;throw error}}
export async function POST(request:NextRequest){try{const access=await requireCasaSuperAdmin();const parsed=bodySchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Invalid CASA membership.",issues:parsed.error.issues},{status:400,headers:casaInternalNoStoreHeaders});const db=getDb();const current=rowsOf<{id:string;role:"CASA_SUPER_ADMIN"|"CASA_TEAM";status:"ACTIVE"|"SUSPENDED"}>(await db.execute(sql`select id,role::text as role,status::text as status from casa_internal_memberships where user_id=${parsed.data.userId}::uuid limit 1`))[0];if(current?.id===access.membership.id&&(parsed.data.role!=="CASA_SUPER_ADMIN"||parsed.data.status!=="ACTIVE"))return NextResponse.json({message:"You cannot demote or suspend your own active Super Admin account."},{status:409,headers:casaInternalNoStoreHeaders});if(current?.role==="CASA_SUPER_ADMIN"&&current.status==="ACTIVE"&&(parsed.data.role!=="CASA_SUPER_ADMIN"||parsed.data.status!=="ACTIVE")){const count=rowsOf<{count:number}>(await db.execute(sql`select count(*)::int as count from casa_internal_memberships where role='CASA_SUPER_ADMIN' and status='ACTIVE'`))[0]?.count??0;if(count<=1)return NextResponse.json({message:"CASA must retain at least one active Super Admin."},{status:409,headers:casaInternalNoStoreHeaders})}const result=await db.execute(sql`insert into casa_internal_memberships(user_id,role,status,created_at,updated_at) select u.id,${parsed.data.role},${parsed.data.status},now(),now() from users u where u.id=${parsed.data.userId}::uuid and u.status='ACTIVE'::user_status on conflict(user_id) do update set role=excluded.role,status=excluded.status,updated_at=now() returning id,user_id,role,status`);const membership=rowsOf<Record<string,unknown>>(result)[0];if(!membership)return NextResponse.json({message:"Active user not found."},{status:404,headers:casaInternalNoStoreHeaders});await writeCasaInternalAudit({access,action:"INTERNAL_MEMBERSHIP_UPSERTED",subjectType:"CASA_INTERNAL_MEMBERSHIP",subjectId:String(membership.id),metadata:{role:parsed.data.role,status:parsed.data.status}});return NextResponse.json({membership},{status:201,headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;throw error}}
