import { createHash, randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { getDb } from "@/db";
import { requireCasaSuperAdmin } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse, casaInternalNoStoreHeaders } from "@/server/internal/http";
import { writeCasaInternalAudit } from "@/server/internal/onboarding";
import { sendAccountAccessEmail } from "@/server/messaging/account-access-email";
export const dynamic="force-dynamic";
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function POST(request:NextRequest,{params}:{params:Promise<{membershipId:string}>}){try{const access=await requireCasaSuperAdmin();const{membershipId}=await params;const db=getDb();const target=rowsOf<{user_id:string;full_name:string;email:string|null;status:string}>(await db.execute(sql`select m.user_id,u.full_name,u.email,m.status::text status from casa_internal_memberships m join users u on u.id=m.user_id where m.id=${membershipId}::uuid limit 1`))[0];if(!target||target.status!=="ACTIVE")return NextResponse.json({message:"Active CASA account not found."},{status:404,headers:casaInternalNoStoreHeaders});const raw=randomBytes(32).toString("base64url");const hash=createHash("sha256").update(raw).digest("hex");const expiresAt=new Date(Date.now()+24*60*60*1000);await db.execute(sql`update casa_account_setup_tokens set used_at=now() where user_id=${target.user_id}::uuid and used_at is null`);await db.execute(sql`insert into casa_account_setup_tokens(user_id,token_hash,purpose,created_by_internal_membership_id,expires_at) values(${target.user_id}::uuid,${hash},'CASA_INTERNAL',${access.membership.id}::uuid,${expiresAt.toISOString()}::timestamptz)`);await writeCasaInternalAudit({access,action:"INTERNAL_ACCOUNT_RECOVERY_LINK_CREATED",subjectType:"CASA_INTERNAL_MEMBERSHIP",subjectId:membershipId,metadata:{targetUserId:target.user_id,targetEmail:target.email}});const origin=new URL(request.url).origin;const setupUrl=`${origin}/account/setup?token=${encodeURIComponent(raw)}`;const emailDelivery=await sendAccountAccessEmail({email:target.email,recipientName:target.full_name,organizationName:"CASA",actionLabel:"Recover CASA Platform Control access",actionUrl:setupUrl,expiresAt,context:"CASA created a private Platform Control password recovery link for your account."});return NextResponse.json({emailDelivery,setup:{url:setupUrl,expiresAt:expiresAt.toISOString()}},{headers:casaInternalNoStoreHeaders})}catch(error){const r=casaInternalAuthErrorResponse(error);if(r)return r;console.error("CASA internal recovery link failed",error);return NextResponse.json({message:"CASA could not create this recovery link."},{status:500,headers:casaInternalNoStoreHeaders})}}
