import { NextRequest,NextResponse } from "next/server";
import { neon } from "@neondatabase/serverless";
import { sql } from "drizzle-orm";
import { z } from "zod";
import { getDatabaseUrl } from "@/config/env";
import { getDb } from "@/db";
import { requireCasaSuperAdmin } from "@/server/internal/authorization";
import { casaInternalAuthErrorResponse,casaInternalNoStoreHeaders } from "@/server/internal/http";
const schema=z.object({feeType:z.enum(["STANDARD_STUDENT","REPLACEMENT_CARD"]),scopeKind:z.enum(["GLOBAL","SCHOOL","BRANCH"]).default("GLOBAL"),schoolId:z.string().uuid().nullable().optional(),branchId:z.string().uuid().nullable().optional(),amountNaira:z.number().min(0).max(100000000),effectiveFrom:z.string().datetime().optional()});
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
export async function GET(){try{await requireCasaSuperAdmin();const db=getDb();const rows=rowsOf(await db.execute(sql`select id,fee_type,scope_kind,school_id,branch_id,amount_kobo,currency,effective_from,effective_to,created_at from casa_pricing_versions order by effective_from desc,created_at desc limit 200`));return NextResponse.json({pricing:rows},{headers:casaInternalNoStoreHeaders})}catch(e){const r=casaInternalAuthErrorResponse(e);if(r)return r;throw e}}
export async function POST(request:NextRequest){try{const access=await requireCasaSuperAdmin();const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the pricing fields."},{status:400,headers:casaInternalNoStoreHeaders});const d=parsed.data;if((d.scopeKind==="SCHOOL"&&!d.schoolId)||(d.scopeKind==="BRANCH"&&(!d.schoolId||!d.branchId))||(d.scopeKind==="GLOBAL"&&(d.schoolId||d.branchId)))return NextResponse.json({message:"Pricing scope does not match the selected school/branch."},{status:400,headers:casaInternalNoStoreHeaders});const schoolId=d.schoolId??null;const branchId=d.branchId??null;const amountKobo=Math.round(d.amountNaira*100);const effective=d.effectiveFrom??new Date().toISOString();const metadata=JSON.stringify({feeType:d.feeType,scopeKind:d.scopeKind,schoolId,branchId,amountKobo,effectiveFrom:effective});const client=neon(getDatabaseUrl());await client.transaction([
 client`insert into casa_pricing_versions(fee_type,scope_kind,school_id,branch_id,amount_kobo,effective_from,created_by_internal_membership_id) values(${d.feeType},${d.scopeKind},${schoolId}::uuid,${branchId}::uuid,${amountKobo},${effective}::timestamptz,${access.membership.id}::uuid)`,
 client`insert into casa_internal_audit_logs(actor_membership_id,school_id,action,subject_type,subject_id,metadata,created_at) values(${access.membership.id}::uuid,${schoolId}::uuid,'INTERNAL_PRICING_CHANGED','CASA_PRICING',null,${metadata}::jsonb,now())`
]);return NextResponse.json({created:true,pricing:{feeType:d.feeType,scopeKind:d.scopeKind,schoolId,branchId,amountKobo,effectiveFrom:effective}},{status:201,headers:casaInternalNoStoreHeaders})}catch(e){const r=casaInternalAuthErrorResponse(e);if(r)return r;console.error("CASA pricing update failed",e);return NextResponse.json({message:"Pricing update failed."},{status:500,headers:casaInternalNoStoreHeaders})}}
