import { redirect } from "next/navigation";
import { sql } from "drizzle-orm";
import { getDb } from "@/db";
import { CasaInternalAccessDeniedError, isAuthRequiredError, requireCasaSuperAdmin } from "@/server/internal/authorization";
import InternalShell from "../internal-shell";
import InternalTeamClient from "./team-client";
function rowsOf<T>(r:unknown):T[]{if(Array.isArray(r))return r as T[];if(r&&typeof r==="object"&&"rows" in r&&Array.isArray((r as {rows?:unknown}).rows))return (r as {rows:T[]}).rows;return []}
type Member = { id:string; user_id:string; full_name:string; email:string|null; phone:string|null; role:"CASA_SUPER_ADMIN"|"CASA_TEAM"; status:"ACTIVE"|"SUSPENDED"; assigned_school_ids:string[]; capabilities:string[] };
type School = { id:string; name:string; slug:string };
export default async function Page(){let access:Awaited<ReturnType<typeof requireCasaSuperAdmin>>;try{access=await requireCasaSuperAdmin()}catch(error){if(isAuthRequiredError(error))redirect("/internal/login");if(error instanceof CasaInternalAccessDeniedError)redirect("/internal");throw error}const db=getDb();const members=rowsOf<Member>(await db.execute(sql`select m.id,m.user_id,u.full_name,u.email,u.phone,m.role::text as role,m.status::text as status,coalesce((select array_agg(a.school_id::text order by a.school_id::text) from casa_internal_school_assignments a where a.membership_id=m.id and a.status='ACTIVE'),array[]::text[]) as assigned_school_ids,coalesce((select array_agg(g.capability::text order by g.capability::text) from casa_internal_capability_grants g where g.membership_id=m.id and g.revoked_at is null),array[]::text[]) as capabilities from casa_internal_memberships m join users u on u.id=m.user_id order by case when m.role='CASA_SUPER_ADMIN' then 0 else 1 end,u.full_name asc`));const schools=rowsOf<School>(await db.execute(sql`select id,name,slug from schools where status='ACTIVE'::school_status order by name asc`));return <InternalShell actorName={access.session.fullName} role={access.membership.role} active="team"><header className="border-b border-black/15 bg-white px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><p className="casa-kicker text-black/45">CASA / Team</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">Internal access control.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-black/50">Create CASA Team identities, designate optional implementation ownership, grant sensitive capabilities, and control internal account status. Every active CASA Team member can onboard students across every active school; ownership is for workload coordination, not access control.</p></header><InternalTeamClient members={members} schools={schools} currentMembershipId={access.membership.id}/></InternalShell>}
