"use client";
import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
const CAPS=["ORGANIZATION_RESTRUCTURE","MASTER_TEMPLATE_ADMIN","CARD_PRODUCTION_ADMIN","IDENTITY_SECURITY_INVESTIGATION","AUDIT_READ","PLATFORM_CONFIGURATION"] as const;
type Member={id:string;user_id:string;full_name:string;email:string|null;phone:string|null;role:"CASA_SUPER_ADMIN"|"CASA_TEAM";status:"ACTIVE"|"SUSPENDED";assigned_school_ids:string[];capabilities:string[]};type School={id:string;name:string;slug:string};
const label=(v:string)=>v.toLowerCase().split("_").map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ");
export default function InternalTeamClient({members,schools,currentMembershipId}:{members:Member[];schools:School[];currentMembershipId:string}){const router=useRouter();const[fullName,setFullName]=useState("");const[email,setEmail]=useState("");const[role,setRole]=useState<"CASA_TEAM"|"CASA_SUPER_ADMIN">("CASA_TEAM");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[credential,setCredential]=useState<{setup?:{url:string;expiresAt:string}|null;existingIdentity?:boolean;membership?:{fullName:string;email:string;role:string}}|null>(null);const[recovery,setRecovery]=useState<{name:string;url:string;expiresAt:string}|null>(null);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("create");setError("");setCredential(null);try{const r=await fetch("/api/internal/access/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName,email,role})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.message==="string"?b.message:"Account creation failed.");setCredential(b);setFullName("");setEmail("");setRole("CASA_TEAM");router.refresh()}catch(x){setError(x instanceof Error?x.message:"Account creation failed.")}finally{setBusy("")}}
 async function recover(m:Member){setBusy(`r:${m.id}`);setError("");setRecovery(null);try{const r=await fetch(`/api/internal/access/accounts/${encodeURIComponent(m.id)}/recovery`,{method:"POST"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.message==="string"?b.message:"Recovery link failed.");if(b.setup)setRecovery({name:m.full_name,...b.setup})}catch(x){setError(x instanceof Error?x.message:"Recovery link failed.")}finally{setBusy("")}}
 async function updateMember(m:Member,next:{role?:Member["role"];status?:Member["status"]}){setBusy(`m:${m.id}`);setError("");try{const r=await fetch("/api/internal/access/memberships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:m.user_id,role:next.role??m.role,status:next.status??m.status})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.message==="string"?b.message:"Membership update failed.");router.refresh()}catch(x){setError(x instanceof Error?x.message:"Membership update failed.")}finally{setBusy("")}}
 async function school(m:Member,id:string,on:boolean){setBusy(`s:${m.id}:${id}`);setError("");try{const r=await fetch(`/api/internal/access/memberships/${encodeURIComponent(m.id)}/schools/${encodeURIComponent(id)}`,{method:on?"DELETE":"PUT"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.message==="string"?b.message:"School assignment failed.");router.refresh()}catch(x){setError(x instanceof Error?x.message:"School assignment failed.")}finally{setBusy("")}}
 async function cap(m:Member,c:string,on:boolean){setBusy(`c:${m.id}:${c}`);setError("");try{const r=await fetch(`/api/internal/access/memberships/${encodeURIComponent(m.id)}/capabilities/${encodeURIComponent(c)}`,{method:on?"DELETE":"PUT"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.message==="string"?b.message:"Capability update failed.");router.refresh()}catch(x){setError(x instanceof Error?x.message:"Capability update failed.")}finally{setBusy("")}}
 return <div className="px-5 py-6 sm:px-8 lg:px-10 lg:py-8">
  {credential?.membership&&<section className="mb-7 border border-black bg-[#e8f2ec] p-5"><p className="casa-kicker text-[#145438]">CASA account created</p><h2 className="mt-3 text-xl font-semibold">{credential.membership.fullName}</h2><p className="mt-2 text-sm">{credential.membership.email} · {credential.membership.role}</p>{credential.setup?<div className="mt-4 border border-black bg-white p-4"><p className="font-mono text-[10px] font-bold uppercase">One-time account setup link</p><p className="mt-3 break-all font-mono text-xs">{credential.setup.url}</p><p className="mt-2 text-xs text-black/50">CASA emails this private setup link automatically when Gmail delivery is available. Keep this copy only as fallback. It expires after 24 hours and becomes unusable after password setup.</p></div>:<p className="mt-3 text-sm">Existing CASA identity linked. They keep their existing password.</p>}</section>}
  <section className="border border-black bg-white"><div className="border-b border-black p-5"><p className="casa-kicker text-black/40">Add internal account</p><h2 className="mt-2 text-2xl font-semibold">CASA Team & administrators</h2></div><form onSubmit={create} className="grid gap-4 p-5 md:grid-cols-[1fr_1fr_220px_auto]"><label className="casa-label"><span>Full name</span><input className="casa-field" value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label className="casa-label"><span>Email</span><input className="casa-field" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="casa-label"><span>Role</span><select className="casa-field" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="CASA_TEAM">CASA Team</option><option value="CASA_SUPER_ADMIN">Super Admin</option></select></label><button className="casa-button-primary self-end" disabled={busy==="create"}>{busy==="create"?"Creating...":"Create account"}</button></form></section>
  {recovery&&<section className="mt-5 border border-black bg-[#e8f2ec] p-4"><p className="casa-kicker text-[#145438]">Password recovery · {recovery.name}</p><p className="mt-3 break-all font-mono text-xs">{recovery.url}</p><p className="mt-2 text-xs text-black/50">Single-use link. Expires after 24 hours.</p></section>}
  {error&&<div className="mt-5 border-l-2 border-[#a12620] bg-[#f6e8e6] px-4 py-3 text-sm text-[#7e1d18]">{error}</div>}
  <section className="mt-7 space-y-5">{members.map(m=>{const self=m.id===currentMembershipId;return <article key={m.id} className="border border-black bg-white"><div className="grid gap-4 border-b border-black/15 p-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">{m.full_name}</h3>{self&&<span className="border border-black px-2 py-1 font-mono text-[9px] uppercase">You</span>}</div><p className="mt-1 text-sm text-black/50">{m.email??m.phone}</p><p className="mt-2 font-mono text-[9px] uppercase text-black/40">{m.role.replaceAll("_"," ")} · {m.status}</p></div>{!self&&<div className="flex flex-wrap gap-2"><button type="button" className="casa-button" disabled={Boolean(busy)} onClick={()=>void recover(m)}>Recovery link</button><button className="casa-button" type="button" disabled={busy===`m:${m.id}`} onClick={()=>void updateMember(m,{status:m.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}>{m.status==="ACTIVE"?"Suspend":"Activate"}</button><button className="casa-button" type="button" disabled={busy===`m:${m.id}`} onClick={()=>void updateMember(m,{role:m.role==="CASA_TEAM"?"CASA_SUPER_ADMIN":"CASA_TEAM"})}>{m.role==="CASA_TEAM"?"Make Super Admin":"Make CASA Team"}</button></div>}</div>{m.role==="CASA_TEAM"&&<div className="grid lg:grid-cols-2"><div className="border-b border-black/15 p-5 lg:border-r lg:border-b-0"><p className="casa-kicker text-black/40">Implementation ownership (optional)</p><p className="mt-2 text-xs leading-5 text-black/45">All active CASA Team members can onboard students for every active school. Select schools here only to mark this person as a primary implementation owner / workload lead.</p><div className="mt-4 flex flex-wrap gap-2">{schools.length===0?<p className="text-sm text-black/50">No schools available.</p>:schools.map(s=>{const on=m.assigned_school_ids.includes(s.id);return <button key={s.id} type="button" disabled={Boolean(busy)} onClick={()=>void school(m,s.id,on)} className={`border px-3 py-2 text-xs ${on?"border-black bg-black text-white":"border-black/20"}`}>{s.name}</button>})}</div></div><div className="p-5"><p className="casa-kicker text-black/40">Sensitive capabilities</p><div className="mt-4 flex flex-wrap gap-2">{CAPS.map(c=>{const on=m.capabilities.includes(c);return <button key={c} type="button" disabled={Boolean(busy)} onClick={()=>void cap(m,c,on)} className={`border px-3 py-2 text-xs ${on?"border-black bg-black text-white":"border-black/20"}`}>{label(c)}</button>})}</div></div></div>}</article>})}</section>
 </div>}
