import fs from "node:fs";
const aws=fs.readFileSync("src/server/biometrics/aws-liveness.ts","utf8");
const scanner=fs.readFileSync("src/app/scanner/scanner-client.tsx","utf8");
const pending=fs.readFileSync("src/app/api/terminal/attempts/pending/route.ts","utf8");
const start=aws.indexOf("export async function startAwsVerificationLiveness");
const end=aws.indexOf("export async function completeAwsVerificationLiveness",start);
if(start<0||end<0||end<=start) throw new Error("Verification liveness function boundary missing");
const verification=aws.slice(start,end);
for(const m of ["LIVENESS_SESSION_EXPIRED","activeSession.providerSessionId","issueAwsLivenessStreamingCredentials(","replayed:","lte("]) if(!verification.includes(m)) throw new Error("Verification liveness recovery marker missing: "+m);
if(verification.includes('"LIVENESS_SESSION_ALREADY_ACTIVE"')) throw new Error("Verification liveness start still strands active sessions behind 409");
for(const m of ["terminalFetchWithRetry","recoverPendingAttempt","/api/terminal/attempts/pending","Pending face verification recovered.","FACE_RETRY","FaceLivenessDetectorCore"]) if(!scanner.includes(m)) throw new Error("Scanner recovery marker missing: "+m);
const faceStart=scanner.indexOf("  const startFace =");
const faceEnd=scanner.indexOf("  const processCard =",faceStart);
if(faceStart<0||faceEnd<=faceStart) throw new Error("Scanner startFace boundary missing");
const face=scanner.slice(faceStart,faceEnd);
const faceUrl="/biometric/liveness/start";
if((face.split(faceUrl).length-1)!==1) throw new Error("Scanner liveness-start URL multiplicity drifted");
const faceUrlIndex=face.indexOf(faceUrl);
if(face.lastIndexOf("await terminalFetchWithRetry(",faceUrlIndex)<0) throw new Error("Scanner liveness-start is not using retry helper");
for(const m of ["authenticateTerminalRequest","getActiveTerminalSession",'"CHECK_IN"','"MATCHED"','"PENDING"',"desc(","duplicatePendingCount","notExists(","studentAttendanceRecords"]) if(!pending.includes(m)) throw new Error("Pending route marker missing: "+m);
if(!/notExists\([\s\S]*studentAttendanceRecords\.schoolId[\s\S]*attendanceVerificationAttempts\.schoolId[\s\S]*studentAttendanceRecords\.sessionId[\s\S]*attendanceVerificationAttempts\.sessionId[\s\S]*studentAttendanceRecords\.studentId[\s\S]*attendanceVerificationAttempts\.studentId/.test(pending)) throw new Error("Pending route does not suppress already-recorded duplicate attempts by school/session/student");
console.log("CASA Scanner pending-attempt recovery contract self-test passed.");
