"use client";
import Link from "next/link";
import { type FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type School={id:string;slug:string;name:string;timezone:string;branch_count:number;student_count:number;status:string;is_assigned:boolean};
type Created={message?:string;school?:{id:string;slug:string;name:string};owner?:{fullName:string;email:string;existingIdentity:boolean;setup?:{url:string;expiresAt:string}|null}};
export default function InternalSchoolsClient({schools,canCreate,isSuperAdmin,openCreateInitially}:{schools:School[];canCreate:boolean;isSuperAdmin:boolean;openCreateInitially:boolean}){
 const router=useRouter(); const [query,setQuery]=useState(""); const [creating,setCreating]=useState(canCreate&&openCreateInitially); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [created,setCreated]=useState<Created|null>(null);
 const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [timezone,setTimezone]=useState("Africa/Lagos"); const [branchName,setBranchName]=useState("Main Campus"); const [branchCode,setBranchCode]=useState("HQ"); const [address,setAddress]=useState(""); const [ownerName,setOwnerName]=useState(""); const [ownerEmail,setOwnerEmail]=useState("");
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?schools.filter(s=>s.name.toLowerCase().includes(q)||s.slug.toLowerCase().includes(q)):schools},[query,schools]);
 const makeSlug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setCreated(null);try{const r=await fetch("/api/internal/platform/schools",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,slug,timezone,headquarters:{name:branchName,code:branchCode,address:address.trim()||null},owner:{fullName:ownerName,email:ownerEmail}})});const b=await r.json().catch(()=>({})) as Created;if(!r.ok)throw new Error(b.message??"School registration failed.");setCreated(b);setCreating(false);router.refresh()}catch(x){setError(x instanceof Error?x.message:"School registration failed.")}finally{setBusy(false)}}
 return <div className="px-5 py-6 sm:px-8 lg:px-10 lg:py-8">
  {created?.school&&<section className="mb-7 border border-black bg-[#e8f2ec] p-5"><p className="casa-kicker text-[#145438]">School registered</p><h2 className="mt-3 text-2xl font-semibold">{created.school.name}</h2><p className="mt-2 text-sm">Workspace: <strong>{created.school.slug}</strong></p>{created.owner?.setup?<div className="mt-5 border border-black bg-white p-4"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em]">School Owner — one-time setup link</p><p className="mt-3 text-sm">Email: <strong>{created.owner.email}</strong></p><p className="mt-2 break-all font-mono text-xs">{created.owner.setup.url}</p><p className="mt-3 text-xs text-black/50">Send this link to the School Owner. They choose their own password; CASA does not create a temporary password.</p></div>:<p className="mt-4 text-sm text-black/55">Existing CASA identity linked; the owner keeps the password already attached to that identity.</p>}<Link href={`/internal/schools/${created.school.id}`} className="casa-button-primary mt-5 inline-flex">Open organization</Link></section>}
  {creating&&canCreate&&<section className="mb-8 border border-black bg-white"><div className="border-b border-black px-5 py-4"><p className="casa-kicker text-black/40">New organization</p><h2 className="mt-2 text-2xl font-semibold">Register a school</h2></div><form onSubmit={submit} className="grid gap-5 p-5 lg:grid-cols-2">
   <label className="casa-label"><span>School / organization name</span><input className="casa-field" value={name} onChange={e=>{const n=e.target.value;setName(n);if(!slug||slug===makeSlug(name))setSlug(makeSlug(n))}} required/></label>
   <label className="casa-label"><span>Workspace slug</span><input className="casa-field font-mono" value={slug} onChange={e=>setSlug(makeSlug(e.target.value))} placeholder="greenfield-school" required/></label>
   <label className="casa-label"><span>Timezone</span><input className="casa-field" value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label><div/>
   <div className="lg:col-span-2 border-t border-black/15 pt-5"><p className="casa-kicker text-black/40">Headquarters</p></div>
   <label className="casa-label"><span>Branch name</span><input className="casa-field" value={branchName} onChange={e=>setBranchName(e.target.value)} required/></label>
   <label className="casa-label"><span>Branch code</span><input className="casa-field font-mono uppercase" value={branchCode} onChange={e=>setBranchCode(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,"").slice(0,32))} required/></label>
   <label className="casa-label lg:col-span-2"><span>Headquarters address</span><textarea className="casa-field min-h-24" value={address} onChange={e=>setAddress(e.target.value)}/></label>
   <div className="lg:col-span-2 border-t border-black/15 pt-5"><p className="casa-kicker text-black/40">First school owner</p></div>
   <label className="casa-label"><span>Owner full name</span><input className="casa-field" value={ownerName} onChange={e=>setOwnerName(e.target.value)} required/></label>
   <label className="casa-label"><span>Owner email</span><input className="casa-field" type="email" value={ownerEmail} onChange={e=>setOwnerEmail(e.target.value)} required/></label>
   {error&&<div className="lg:col-span-2 border-l-2 border-[#a12620] bg-[#f6e8e6] px-4 py-3 text-sm text-[#7e1d18]">{error}</div>}
   <div className="flex gap-3 lg:col-span-2"><button disabled={busy} className="casa-button-primary">{busy?"Registering...":"Register school"}</button><button type="button" className="casa-button" onClick={()=>setCreating(false)}>Cancel</button></div>
  </form></section>}
  <section className="mb-6 border border-black bg-[#e8f2ec] p-4"><p className="casa-kicker text-[#145438]">Universal onboarding access</p><p className="mt-2 text-sm leading-6 text-black/65">All active CASA Team members can open every active school and register/onboard students. An implementation owner is only the team member primarily responsible for coordinating that school&apos;s workload.</p></section>
  <section className="border border-black bg-white"><div className="flex flex-col gap-4 border-b border-black p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="casa-kicker text-black/40">Organizations</p><h2 className="mt-2 text-2xl font-semibold">{schools.length} registered school{schools.length===1?"":"s"}</h2></div><div className="flex gap-3"><input className="casa-field min-w-64" placeholder="Search school or workspace" value={query} onChange={e=>setQuery(e.target.value)}/>{canCreate&&<button className="casa-button-primary" type="button" onClick={()=>{setCreated(null);setCreating(true)}}>Register new school</button>}</div></div>
   {filtered.length===0?<div className="p-8 text-sm text-black/50">{schools.length===0?"No school has been registered yet.":"No organization matches this search."}</div>:<div>{filtered.map(s=>{const active=s.status==="ACTIVE";const badge=isSuperAdmin?"Platform authority":s.is_assigned?"Implementation owner":"Shared onboarding";const body=<><div><h3 className="text-lg font-semibold">{s.name}</h3><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-black/40">{s.slug} · {s.status}</p>{active&&!isSuperAdmin&&!s.is_assigned&&<p className="mt-2 text-xs text-black/45">Open to the CASA Team for student onboarding; no primary implementation owner has been set.</p>}</div><span className="border border-black/20 px-2 py-1 font-mono text-[9px] uppercase text-black/55">{badge}</span><p className="text-sm text-black/50">{s.branch_count} branches</p><p className="text-sm text-black/50">{s.student_count} students</p></>;return active?<Link key={s.id} href={`/internal/schools/${s.id}`} className="grid gap-4 border-b border-black/15 p-5 last:border-b-0 hover:bg-[#f2f2ef] sm:grid-cols-[minmax(0,1fr)_auto_auto_auto] sm:items-center">{body}</Link>:<div key={s.id} className="grid gap-4 border-b border-black/15 bg-black/[0.02] p-5 last:border-b-0 opacity-65 sm:grid-cols-[minmax(0,1fr)_auto_auto_auto] sm:items-center">{body}</div>})}</div>}
  </section>
 </div>
}
